### ISSUE TITLE
Niina: Arkistoyksikkö: Lisää näkyviin sarjan metatieto Järjestämiseen liittyvät tiedot

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#100]
"SARJAT: sarjan metatieto "järjestämiseen liittyvät tiedot" tulisi näkyä arkistoyksiköllä, kuten muutkin sarjan lisätiedot"

**Comment by mustakostaja** [comment]
Mihin tämä tieto pitäis lisätä arkistoyksiköllä? Tuohon sarjan lisätiedot -laatikkoon vai tehdäänkö oma?

**Comment by minna-aaltonen** [comment]
Arkistonmuodostaja ja sarja osioon omana kenttänään. Ymmärtäisin näin. :)

**Comment by minna-aaltonen** [comment]
Kenttä lisätty.
