### ISSUE TITLE
Niina: Hävitysehdotukset: Hävitysehdotus ponnahdusikkunassa arkistoyksiköt pitäisi järjestää kuten päänäkymässä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#103]
"HÄVITYS: Hävityehdotuksen arkistoyksiköt pitää olla näytöllä ja tulostettavassa hävitysehdotuksessa järjestetty samoin kuin perusnäkymässä (kaavan mukainen, rajavuodet…)"

**Comment by KelaTest** [comment]
tämä on mielestämme kiireisesti korjattava. N&P

**Comment by KelaTest** [comment]
lisäsimme tänne kriittinen-leiman. 
tarkennan vielä alkuperäistä sanamuotoa, jotta se on selkeämpi.

**Comment by KelaTest** [comment]
Tässä tarkemmin muotoiltu kuvaus asiasta: 
Hävitysehdotuksen näyttöluettelon arkistoyksiköt tulee järjestää hierarkkisesti Sarjan nimen&tunnuksen mukaiseen hierarkiaan samoilla jatkosäännöillä kuin perusnäkymä/muut näkymät (=rajavuosien mukaan > arkyks jno mukaan jne). Tällä hetkellä hävitysehdotusnäkymäluettelo on vielä sekaisin. 

Näyttöluettelon sarakejärjestys on muuten ok. 

Hävitysehdotuksen tulosteeseen liittyvät kommentit on kirjattu eri issueen.
(niina)

**Comment by ArnoSaine** [comment]
Arkistoyksiköitä ei enää listata hävitysehdotuksen ponnahdusikkunaan.
