### ISSUE TITLE
Niina: Hävitysehdotukselta puuttuu säilytysyksiköiden kokonaismäärä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#105]
Lisätään hävitysehdotuksen perustietoihin **säilytysyksiköiden** kokonaismäärä.

Tästä on olemassa vaatimus: Liite_4: Liite 4.5 Raportit ja tulosteet, solu E9

"HÄVITYS: hävitysehdotukselta puuttuu säilytysyksiköiden kokonaislukumäärä (vrt. vaatimusmäärittelyt tarkennus/4.4. E9). Voisiko mahdollisesti ilmoittaa hävityeshdotuksen perustiedoissa (= ennen luetteloa)?"

**Comment by mustakostaja** [comment]
Lisätty säilytysyksiköiden kokonaismäärä ennen kaavaluetteloa.

**Comment by minna-aaltonen** [comment]
Tulosteessa on säilytysyksiköiden määrä ennen kaavaluetteloa.
