### ISSUE TITLE
Massamuokkaus: Kenttien Säilytysaikatyyppi ja Säilytysaika (vuotta) pitäisi olla vaihtoehtoiset kuten Arkistoyksikkö ponnahdusikkunassa

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#113]
Nyt käyttäjä voi asettaa ARKISTOYKSIKÖIDEN MASSAMUOKKAUS ponnahdusikkunassa sekä Säilytysaikatyyppi että Säilytysaika (vuotta) kenttiin arvon, jolloin Arkistoyksikkö ponnahdusikkunassa molemmat kentät ovat inaktiivisia ja niitä ei voi sieltä käsin enää muuttaa.

**Comment by minna-aaltonen** [comment]
Mikäli toinen kentistä valitaan, myös toisen pitäisi muuttua muokatuksi, jotta ei käy niin, että tietokantaan tallentuu arvo molempiin tai ei kumpaankaan kenttään.

**Comment by minna-aaltonen** [comment]
Nyt toimii hienosti.

**Comment by mustakostaja** [comment]
Edelleen mahdollista tallentaa molemmat arvot.

**Comment by minna-aaltonen** [comment]
Eh, niin tosiaan olikin. No, mutta nyt ihan oikeasti toimii kuten pitäisi.
