### ISSUE TITLE
Arkistoyksiköiden massamuokkaus: Rajavuodet: Pakollisen arvon voi tyhjentää ja ei ole mahdollista muokata ainoastaa toista Rajavuodet kentistä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#114]
* Rajavuodet alku ja Rajavuodet loppu ovat pakollisia kenttä arkistoyksikölle, mutta ne voi massamuokkauksella tyhjentää. (Korjattu)
* Jos muokkaa toista Rajavuodet kenttää niin myös toinen muuttuu muokatuksi ja siitä joko pyyhkiytyy arvo tai sille on annettava arvo. (Korjattu)

**Comment by minna-aaltonen** [comment]
Tiina (1.4.2015): Joko ei tyhjää ei voi muokatusta valita lainkaan tai tyhjän arvon tallennus estetään.

**Comment by minna-aaltonen** [comment]
Muuten korjaus näyttäisi olevan kunnossa, mutta edelleen molemmat kentät muuttuvat vihreiksi ja siitä syntyy mielikuva, että molempia myös muokataan vaikka näin ei enää tapahdukaan. Ainoastaan sen kentän pitäisi muuttua vihreäksi, jonka arvoa myös tullaan muuttamaan.

**Comment by minna-aaltonen** [comment]
Vähän hämmentävästi toimii edelleen. Nyt kun antaa rajavuosien alku kenttään arvon (numeron tai ei validin arvon) ja ottaa sen sitten pois niin **Rajavuodet** loppu kenttä muuttuu muokatuksi (vihreä) ja alku muuttuu takaisin muokkaamattomaksi (valkoinen). Muuten näyttäisi olevan kunnossa.

**Comment by mustakostaja** [comment]
Sama ongelma taitaa ilmetä myös arkistoyksikön muokkauksessa. 
Vaarana, että toisen arvon muokkaus ja pyyhintä vaikuttaa myös toiseen raja-arvoon.

**Comment by minna-aaltonen** [comment]
Nyt näyttäisi olevan ok.
