### ISSUE TITLE
Aineistohaku | Arkistoyksiköiden massamuokkaus: Ei anna käyttäjälle palautetta siitä onko muokkaus mennyt jo läpi

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#116]
Käyttäjä ei tiedä onko massamuokkaus vielä käynnissä vai ei. Ison aineiston massamuokkaus kestää kauan ja haku massamuokkauksen jälkeen antaa sekavia tuloksia, kun osa muutoksista on jo mennyt läpi ja osa ei.

**Comment by ArnoSaine** [comment]
Muutokset päivittyvät näytölle tietokannasta vähitellen, mutta hakujen tulisi antaa oikeat tulokset heti kun ikkuna on suljettu.

**Comment by minna-aaltonen** [comment]
Nyt on huomattavasti selkeämpi, käyttäjä on paremmin kärryillä sen suhteen mitä tapahtuu.
