### ISSUE TITLE
Niina: SARJA: Sarjat eivät näy tunnuksen mukaan aakkosjärjestyksessä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#130]
![sarjan tietojen muuttaminen](https://cloud.githubusercontent.com/assets/8858834/7066044/156d7454-dec7-11e4-8ba8-4273df2684ca.png)

Tunnusten aakkostusongelma myös täällä: Niina: Arkistonmuodostaja | Arkistokaava taulukko: Sarjat eivät näy tunnuksen mukaan aakkosjärjestyksessä #87

"Otin arkmun kansainvälisten asiain keskus. Loin sinne pääsarjan A. Valitsin kaavalta sarjan Ba tarkoituksenani siirtää se A-sarjaan. Kun painoin sarjan vaihtamisruudussa isoa B-kirjainta, saan valikon, jossa luomani A on viimeisenä, kun sen pitäisi olla ensimmäisenä."

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)
