### ISSUE TITLE
Niina: Sisäänkirjautuminen ja uloskirjautuminen eivät toimi oikein

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#140]
Minna: En pysty toistamaan ongelmaa, Niinalta pyydetty lisää apua. Ruudunkaappauksesta nähdään, että päänäkymä toimii kuten käyttäjä olisi peruskäyttäjä (puuttuu **Lisää arkistonmuodostaja**, arkistoyksiköiden luonti on sallittu vain alimman sarjatasolle), mutta käyttäjänimenä näkyy pääkäyttäjä.

Niina: "Kirjauduin ulos pääkäyttäjältä ja kirjauduin sisään peruskäyttäjänä. Käyttäjäroolina näkyy edelleen pääkäyttäjä, mutta toiminnot näyttäisivät olevan peruskäyttäjätoimintoja."

![kirjautuminen sarjan nimet varillisia](https://cloud.githubusercontent.com/assets/8858834/7111743/c7f805f6-e1cb-11e4-97c5-3fae37f7aed8.png)

**Comment by KelaTest** [comment]
Kokeilin tätä tänään moneen kertaan renkkaamalla, ei toistu.

**Comment by minna-aaltonen** [comment]
Suljen tämän ja avataan se uudelleen, jos virhe saadaan toistumaan.
