### ISSUE TITLE
Niina: ARKISTOYKSIKKÖ ja SARJA: Kenttien nimet ja niissä näytettävät tiedot

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#142]
**SARJA** 
* Kentän **Suhde** nimi pitäsi olla **Aineistoviite**

**ARKISTOYKSIKKÖ**
* **Aineistoviite** (entinen sarja ikkunan **Suhde** kenttä) tulee **Liittyvät sarjat** kenttään, pitäisi tulla **Aineistoviite** kenttään.

Niina: "Kun valitsee arkistyksikön kortilta painikkeen muokkaa sarjan tietoja, on tällä sarjan kortilla eri nimet kuin arkyksnäkymässä. (kuvakaappaus Sarjan tiedot). Sarjakortilla kentän SUHDE nimi tulee olla ”aineistoviite”. Kun kirjaa kenttään SUHDE, tieto siirtyy arkyksnäkymässä kohtaan ”liittyvät sarjat” kun pitäisi siirtyä kohtaan ”aineistoviite”."

**Comment by minna-aaltonen** [comment]
Ei ole ainakaan kokonaan korjattu. Sarjalla on kenttä **Suhde** ja sen tiedot kopioituvat kenttään **Aineistoviite**.

**Comment by mustakostaja** [comment]
Taitaa olla korjattuna jo ennestään.

**Comment by minna-aaltonen** [comment]
Nyt on kokonaan korjattu.
