### ISSUE TITLE
Paula: IE11: Numerokenttien validointi ei toimi

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#144]
Kun käyttää selaimena Internet Explorer 11:sta ja tallettaa numerokentäksi määrättyyn kenttään ei-numeerisen arvon, ei anna virheilmoitusta vaan tallettaa vain tyhjää.

**Comment by mustakostaja** [comment]
Mahdollisesti voidaan korjata niin, että asetetaan regexp pattern, joka syö vain lukuja. Tämä tosin tarkoittaa, että numero-kentät pitäisi vaihtaa tekstikentiksi.

**Comment by minna-aaltonen** [comment]
En näe mitään ongelmaa siinä, että olisivat tekstikenttiä.
