### ISSUE TITLE
Nimiö | Hävitettävissä / Hävitysaika: ei tulostu nimiölle

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#156]
Vaikka arkistoyksiköllä on **Hävitettävissä** tieto, se ei tulostu nimiölle **Hävitysaika** kenttään. Onkohan kenttien nimet tarkoituksella toisistaan poikkeavat?

**Comment by minna-aaltonen** [comment]
**Ala-arkistonmuodostaja** kentän tulostumista ei voi testata, koska kenttä puuttuu tällä hetkellä **ARKISTONMUODOSTAJA** kortilta.

**Comment by mustakostaja** [comment]
Ala-arkistonmuodostaja tulee arkistoyksikkö-kortille (korjattu).

**Comment by minna-aaltonen** [comment]
* Hävitettävissä tieto tulee nimiölle. 
* Ala-arkistonmuodostaja tulee nyt ARKISTOYKSIKKÖ kortille ja näkyy nimiössä.
