### ISSUE TITLE
Niina: Nimiö: Tulosteen muotoiluongelmia

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#160]
* "Puuttuu Kela-logo nimiö tulosteen vasemmasta yläkulmasta"
* " Skaalaus ei sovi vaakatulostukseen (liite nimiö-1). Toimittamassamme mallissa osuu vaakatulosteeseen täysin. Saan tuon teidänkin mallin sopimaan vaakamoodiin, kun muutan tulostustoiminnassa reunukset. Olisiko mahdollista, että tarkistaisitte kuitenkin vielä tuon mallinne reunukset (meidän mallissa kaikki reunukset arvo 0), jos se tuolla korjaantuisi ja tulisi suoraan vaakapaperiin sopiva tuloste. Skaalaukset meidän mallissa = ”ei skaalausta”."
* "Testasimme tulosteita; joillain tulostimilla tulee normaalisti ja toisilla tulee hirvittävä määrä tyhjiä sivuja perään (arkistoyksikkönäkymä ja säilytysyksikönäkymä 10-sivuisena joista 7 ja 9 tyhjää sivua) Näyttäisi olevan tulostimiin liittyvä ongelma. Esim. arkistoyksikkö ID: 135068"

**Comment by KelaTest** [comment]
Mielestämme nimiöt tulee olla kunnossa käyttöönottoon mennessä. Ne ovat ensimmäisiä konkreettisia asioita mitä tarvitaan ja niitä aletaan myös heti ottamaan. Ei tule mitään, jos kaikki asetukset ovat pielessä. Tämän päivän testissä nimiöitä tulee kolme yhteen sivuun > automaattisesti menee tarratulostus pieleen ja tarrat hukkaan. Nimiön pitää olla sellainen, että voimme sen suoraan tulostaa, eikä meidän tarvitse muotoilla joka kerta joka nimiötä kokonaan uusiksi. Tähän automaattinen nimiön tulostamistoiminto perustuu.
Kelan logo oli annetussa nimiömallissa, se pitäisi saada nimiöön mallin mukaiseen paikkaan. 
(niina)

**Comment by minna-aaltonen** [comment]
Tiina voisi kommentoida tätä.

**Comment by KelaTest** [comment]
Jäi äsken mainitsematta, että nyt tulosteeseen tulee kolme etikettiä sivulle, kun pitäisi tulla neljä.

**Comment by minna-aaltonen** [comment]
Tällä hetkellä:
* Kela logo ei vielä näy oikein Excelillä
* Nyt tulee jo neljä etikettiä sivulle

**Comment by KelaTest** [comment]
KOTTO tuotanto (niina)
Logo ei tulostu oikein.
nimiömalli osittain korjaantunut. Ensimmäinen sivu tulostuu oikein neljä etikettiä ja menevät tarrapohjaan oikein. Seuraavan (kakkos)sivun etiketit alkavat venyä pituussuunnassa siten, että viimeinen rivi (säilyksnro) menee kolmannelle sivulle. 

En pysty liittämään tähän exceleitä, mutta laitan teille sähköpostilla nimiöstä tällä hetkellä saatavan excel-tiedoston; tulostusaluemäärityksestä näette rivityksen ongelman. 

Lisää samaan sähköpostiin viimeisimmän lähettämämme nimiömallin. 

Viitteenä: olemme käyneet tästä sähköpostikirjeenvaihtoa 8.4. (viimeisin nimiömalli) ja 16.4./17.4./21.4, jossa totesimme mm. näin: 
"Olisiko vaikutusta sillä, että mallissanne on edelleen vähän eri asetukset kuin Kelamallissa? Katsoin, että sarakeleveydet on pikkusen eri kuin meidän mallissa, myös tekstien tasaukset on vähän eri (otsikkoriveillä pitäisi olla tasaus ylös keskelle jne) Luulen, että toi mahtumisongelma tulee rivikorkeusasetuksista; Kelamallissa rivikorkeus otsikoissa on 14 pistettä, teidän mallissa 15 pistettä. En tarkistanut näitä tämän enempää, mutta sovituksen ratkaisut löytynevät tarkistamalla kaikki noi. Oletuksella, että olette tehneet oman mallin, olisiko helppoa/mahdollista, että saisitte ton meidän mallin sinne purkkiinne noine asetuksineen? Näin saataisiin kaikki asetukset kerralla täsmälleen samanlaisiksi. "
Vertailun vuoksi, nyt KOTTO tulevassa nimiömallissa rivikorkeus otsikoissa 15,75.

**Comment by mustakostaja** [comment]
Tiivistetty nimiön pohjaa, jotta etiketit mahtuvat yhdelle sivulle. Kuva toimii mac office 2011 versiolla.

**Comment by KelaTest** [comment]
Ei kunnossa vieläkään. Olemme täällä päässä tutkineet (kuvattu myös yllä), että virhe johtuu rivikorkeuksista, jotka toimittamassamme mallissa ovat ok. järjestelmän tuottamassa mallissa rivikorkeudet ovat eri, mistä syystä ei tule oikein tulostuksessa. 
Massatulostuksessa menee nyt niin, että seuraavan sivun logot tulevat ensimmäiselle sivulle, kolmannen sivun logo ja ensimmäinen rivi toiselle sivulle jne. Nimiö on korkeussuuntaan siis liian matala. Rivinkorkeuksien säätö Kelan mallin mukaiseksi pitäisi ratkaista asia.
