### ISSUE TITLE
IE11: Aineistohaku: Osasanahaun ja skandimerkkien kanssa ongelmia

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#165]
Kentät, joissa on osasanahaku eivät anna osasanahaulle hakutuloksia IE 11 selaimella:
* **Ala-arkistonmuodostaja**
* **Arkistoyksikön nimi**
* **Nimen tarkenne**
* **Säilytysajan peruste**
* **Salassapitoperuste**
* **Lisätiedot**
* **Kuvailu**
* **Järjestämiseen liittyvät tiedot**
* **Näyte, otanta**
* ja luultavasti myös ARTI kentissä

Esim: Ala-arkistonmuodostaja (tuotantodatan arkistonmuodostaja Työterveysneuvottelukunta):
* Sairausvakuutusosasto -> Palauttaa kaikki aineistot, joissa ala-arkistonmuodostaja on "Sairausvakuutusosasto".
* Sairausvakuutuso -> Hakutulos 0, vaikka edellisessä haussa on tullut tuloksia. 

Lisäksi skandimerkkien tulkinnassa on em kentissä jotain ongelmaa. Esimerkiksi:
* **Arkistonmuodostaja**: Työterveysneuvottelukunta
* **Arkistoyksikön nimi**: TYÖTERVEYSHUOLTONEUVOTTELUKUNTA -> ei löydä mitään
* **Arkistoyksikön nimi**: TYOTERVEYSHUOLTONEUVOTTELUKUNTA -> eli kun (ö->o) löytää aineistot, vaikka nimessä nimenomaan on ö eikä o

**Comment by minna-aaltonen** [comment]
Tämä vika ei näytä korjaantuneen, esim:
* **Ala-arkistonmuodostaja**: Ei toimi, esim Sairausvakuutusosa ei palauta mitään vaikka Sairausvakuutusosasto palauttaa.
* **Arkistoyksikön nimi**: KELAN TYÖTERVEYSHUOLTONEUVOTTELUKUNTA palauttaa arkistoyksikköjä, mutta KELAN TYÖTERVEYSHUOLTONEUVOTT ei palauta mitään

Ongelma skandimerkkien kanssa näyttäisi korjaantuneen.

**Comment by minna-aaltonen** [comment]
Ei toimi edelleenkään:
* **Ala-arkistonmuodostaja**
* **Arkistoyksikön nimi**
* **Nimen tarkenne**
* **Säilytysajan peruste**

Muita en edes lähtenyt testaamaan, kun ilmeisesti tässä korjauksessa on selvästi nyt jotain ongelmaa.

**Comment by minna-aaltonen** [comment]
Nyt näyttäisi aineistohaun osasanahaku ja skandimerkit toimivan kuten pitää.

**Comment by KelaTest** [comment]
IE11-testauksessa löytyi samoja vikoja. Testasin hakuja mm.kentistä ala-arkistonmuodostaja,  nimen tarkenne,salassapitoperuste, lisätiedot ja kuvailu sekä järjestämiseen liittyvät tiedot :  'emal' haulla löytyy 'önskemål' ja 'MÅL'-haulla 'MAL, 'öss'- haulla 'OSS', 'paallikko''-haulla 'päällikkö' jne.

**Comment by KelaTest** [comment]
pikatestillä ok > tuotantoon
