### ISSUE TITLE
Aineistohaku | Hakutulos: Taulukossa näytettävät tiedot pitäisi voida valita

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#167]
Ongelma: Hakutulos taulukossa ei näy (eikä mahdu näkymään) kaikkia arkistoyksikön kenttiä, joten tilanteessa, jossa halutaan poimia massamuokattavia kenttiä jonkin nyt ei taulukossa näkyvän tiedon perusteella, arkistoyksikön tiedot joudutaan avaamaan.

Niina: "Hakutuloksissa pitäisi olla aina myös se haettu asia tuloksena. (Mielestäni on jossain puhuttu siitäkin, että sarja pitäisi näkyä tuloksissa myös, samoin tulosten näyttämisen järjestyksestä listalla; en lähde niitä kertaamaan kun en tarkalleen muista mitä on jo reklamoitu, katsotaan sitten kun githubin avoimet on käyty kaikki läpi ja korjattu). Mulla on tästä nyt käyttötapaus:

Jos haen esim. otanta-aineistoja, en voi tietää tarkalleen miten otannat on kirjattu. Konversiomatskussa on eri variaatiot vakioitu, mutta normikäytössä vaihtelua kirjoitustapaan ja asuun tulee väistämättä, vaikka kyseessä olisi sama otanta. (yleisimmin se on meillä 18s ja 28s syntyneet, mutta se voi olla myös 8, 18 ja 28 syntyneet tai jotain aivan muuta; käyttäjä ei voi tietää, mitä otantoja mahdollisesti on kirjattu ja miten [vrt. käyttämäni kirjoitusasut yllä], joten hänen pitää hakea ensin ne kaikki näkyviin.)

Jos nyt haluaisin massamuokata esim. Eläkeosaston otanta-aineistoja, vaikka itse otantatietoa, en pysty nykyisten hakutulosten perusteella rajaamaan joukkoa, koska voin käytännössä hakea vain yleisellä sanalla ”otanta”. Massamuokkausta varten valittavaa joukkoa tulisi voida tarkentaa hakutuloksissa näkyvän kysytyn tiedon perusteella. "

**Comment by KelaTest** [comment]
Tämä on kommentoitu spostilla, liittyy/on samaa kuin issue 172. N&P

**Comment by minna-aaltonen** [comment]
Suljetaan duplikaattina issuelle  Niina: Aineistohaku | Hakutulos: Taulukossa ei ole riittäviä tietoja, jotta voitaisiin valita massamuokattavat arkistoyksiköt #172
