### ISSUE TITLE
ARKISTOYKSIKKÖ | Kielet: Alasvetovalikon valintojen pävittäminen

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#170]
Valintojen pitäisi olla: 
1. fin
2. swe
3. eng
4. dan
5. fre
6. ger
7. rus
8. spa
9. ara
10. alb
11. kur
12. per
13. som
14. muu kieli

**Comment by minna-aaltonen** [comment]
Odottaa asiakkaalta vahvistusta, että yllä oleva lista on nyt ok.

**Comment by KelaTest** [comment]
on ok. N&P
