### ISSUE TITLE
Niina: Aineistohaku | Hakutulos: Taulukossa ei ole riittäviä tietoja, jotta voitaisiin valita massamuokattavat arkistoyksiköt

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#172]
Muutosten toteutustapa pitää neuvotella.

**Comment by KelaTest** [comment]
tähän vastattu sähköpostilla. N&P

**Comment by minna-aaltonen** [comment]
Sovittu sähköpostissa asiakkaan kanssa ( 21 May 2015 ): Massamuokattavat tiedot lisÃ€tÃ€Ã€n hakutulostaulukkoon kiinteiksi sarakkeiksi

**Comment by minna-aaltonen** [comment]
Niina kirjoitti issuessa #247: 
Aineiston hakutuloksista puuttuu edelleen arkistonmuodostaja- ja sarjan nimi&tunnus-tiedot sekä arkistoyksikön jno. Näyttäminen pitää muutoin olla normaalissa perusnäkymän mukaisessa hierakiassa (nykyisten tietojen sarakejärjestys on ok).

Tämä liittyy issue 172:een, mutta teen siihen tarkennuksen. 

Kun hakutulokset näytetään, tulisi ensin näkyä Arkistonmuodostaja, Sarjan tunnus&nimi, Arkistoyksikön jno ja sitten siinä järjestyksessä kuin nyt on; nämä ovat mielestämme kiireellisiä, koska vaikuttavat moneen perusasiaan/-hakemiseen.

Sitten ne muut tiedot, jotka jäävät scrollin taakse oikealle, eivät ole niin kiireellisiä, koska liittyvät massamuokkausten tekemiseen, eikä niitä aleta heti ensimmäiseksi tehdä.

(niina)

**Comment by KelaTest** [comment]
Huom, 
toimituksesta puuttuu vielä massamuokattavat tietokentät.
******************************************************************************************
minna-aaltonen  commented on May 27  
Sovittu sähköpostissa asiakkaan kanssa ( 21 May 2015 ): Massamuokattavat tiedot lisÃ€tÃ€Ã€n hakutulostaulukkoon kiinteiksi sarakkeiksi

Hakutulostaulukkoon lisÃ€tÃ€Ã€n siitÃ€ vielÃ€ puuttuvat massamuokattavat kentÃ€t sarakkeiksi, tÃ€llÃ¶in taulukon leveys kasvaa todennÃ€kÃ¶isesti yli nÃ€ytÃ¶n leveyden, joten sivua on skrollattava vaakasuunnassa, jotta kaikkien sarakkeiden tiedot nÃ€kyvÃ€t

*******************************************************************************************
Tässä vielä yllä mainittu sposti 21.5.2015, joista sovittu toteutustavaksi vaihtoehto 1:
Hei!

Muistaakseni sovittiin tästä jo, että valitaan tuo vaihtoehto 1. Tässä joka tapauksessa kirjallinen vahvistus.

Ystävällisin terveisin
Paula Karilas
Kela, IT-osasto
Nordenskiöldinkatu 12 , 00250 HELSINKI
puh. 020 6341876  tai   050 5518087
paula.karilas@kela.fi

Lähettäjä: Tiina Isotalo [mailto:tiina.isotalo@vismaconsulting.fi] 
Lähetetty: 12. toukokuuta 2015 9:45
Vastaanottaja: Vaartio Niina
Kopio: Karilas Paula; Happonen Matti
Aihe: Hakutulostaulukon näytettävät sarakkeet

Hei,

Tässä nämä ehdotukset vaihtoehtoisista ratkaisutavoista massamuutettavien tietojen näyttämiselle hakutulostaulukossa.

 1)Massamuokattavat tiedot lisätään hakutulostaulukkoon kiinteiksi sarakkeiksi (ei lisätyö)

Hakutulostaulukkoon lisätään siitä vielä puuttuvat massamuokattavat kentät sarakkeiksi, tällöin taulukon leveys kasvaa todennäköisesti yli näytön leveyden, joten sivua on skrollattava vaakasuunnassa, jotta kaikkien sarakkeiden tiedot näkyvät

Tähän nykyiseen lisättäisiin siis vielä esim. salassapitoaika, salassapitoperuste, kielet, arkistoyksikön laatu, kustannuspaikka, lisätiedot eli kaikki sarakkeet massamuokkausnäkymästä:

 2)Kustomoitava sarake (lisätyö, työmääräarvio 6 htp)
[...]

terveisin,
Tiina

Tiina Isotalo
Visma Consulting Oy
GSM +358 45 6364 099
tiina.isotalo@vismaconsulting.fi
Hatanpään valtatie 26, 6. krs
33100 Tampere
www.vismaconsulting.fi
Helsinki, Tampere

**********************************************************************************************
Massamuokattavat kentät on määritelty dokumentissa Aineistohaut ja massamuokkaus_toimittajalle_2015-04-08.xls, koosteena alla:
ala-arkistonmuodostajan nimi
arkistoyksikön nimi
arkistoyksikön nimen tarkenne
aineiston rajavuodet - alkuvuosi
aineiston rajavuodet - loppuvuosi
arkistoyksikön laatu
kieli
säilytysaika (vuosia)
säilytysaika (muu arvo)
säilytysajan peruste
henkilötieto
julkisuus
salassapitoaika
salassapidon päättymisajankohta
salassapidon peruste
lisätieto
Kustannuspaikka (ARTIsta tuotava tieto)
säilytysyksikön laatu
säilytysyksikön leveys
sijainti: huone
sijainti: hylly
sijainti: taso

**Comment by KelaTest** [comment]
- aineiston hakutuloksista puuttuu vielä seuraavat metatietosarakkeet (sijoitetaan jonon jatkoksi oikealle): 
ala-arkistonmuodostajan nimi
 arkistoyksikön laatu
 kieli
  säilytysajan peruste
 salassapitoaika
 salassapidon päättymisajankohta
 salassapidon peruste
 lisätieto
 Kustannuspaikka (ARTIsta tuotava tieto)

- massamuokkaus-välilehdellä on kaikki edellisessä kommentissa mainitut tiedot; kenttänimi Säilytysaikatyyppi tulee muuttaa > Säilytysaika (muu arvo)

- hakulomakkeen kieli-valikosta puuttuu kieliä (ei sama valintalista kuin arkyks kirjausnäkymässä)

Laitan tämän vain huomioksi tähän, sillä kirjoitan kattavammin spostiin (NVA/3.11.2015): ARNO kommentoi 30.10.2015: Hakutuloksen järjestetään, mikäli tuloksia on 200 tai vähemmän. Määrää on varaa nostaa kenties 1000 arkyksikköön ilman suurta vaikutusta suorituskykyyn, muttei 35 000. 
Tarkoittaako tämä, että hakutuloksia ei järjestetä ollenkaan, jos tuloksia on yli 200 (yli 1000)? Vai järjestetään, mutta suorituskykyyn jää puutteita?
