### ISSUE TITLE
Aineistohaku | Rajavuodet: Haku pelkästään toisella rajavuodella palauttaa aina myös tyhjät rajavuodet

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#176]
Kun teen haun rajavuosilla <ei muokattu> - 1910, saan tulokseksi 30 aineistoa, joille ei rajavuositietoa ole annettu. Haku 2034 - <ei muokattu> palauttaa saman hakutuloksen. Tyhjät vuodet ovat mukana kaikissa hakutuloksissa. 

Sukua jo korjatulle ongelmalle: Paula: Aineistohaku: Tyhjät rajavuodet aiheuttavat vääriä hakutuloksia - onko konversio-ongelma? #93

**Comment by mustakostaja** [comment]
Kuinka pitäisi toimia? Haetaanko tyhjät ainoastaan jos rajakenttien arvot ovat tyhjiä?

**Comment by minna-aaltonen** [comment]
Kelalle lähetetty kysymys, johon odotetaan vastausta ennen kuin edetään tämän kanssa:

Mietimme täällä miten ARTI:n pitäisi reagoida siihen, että arkistoyksikön rajavuositieto on tyhjä?

Meillä on nyt issue:
﻿https://github.com/Proactum/ARTI/issues/176#issuecomment-97664921

Eheyssääntöjen mukaan ARTI tarkistaa, että arkistoyksiköillä on aina rajavuodet eli tämä ongelma tulee siitä, että konversiossa kantaan viedyille aineistoille ei kaikille ole annettu rajavuosia. Olisko mahdollista, että Kela korjaisi konvertoitavaa aineistoa niin että kaikilla aineistoilla olisi rajavuodet? Silloin tälle hakutoiminnolle ei tarvitsisi tehdä ohjelmallisia korjauksia, koska tälläisia aineistoja ei järjestelmässä pitäisi olla.

**Comment by minna-aaltonen** [comment]
Niina: tässä räknäsimme ja tulimme tulokseen että korjaamme noille vuosiluvuksi 9999 raja alku ja loppu-kenttiin. Silloin tarkistus ei herjaa mutteivät turhaan nouse hakutuloksiin. Teemme näistä korjaukset konversiomatskuun.

-> KORJAUSTA EI TARVITA
