### ISSUE TITLE
Artturi: ARKISTOYKSIKÖIDEN MASSAMUOKKAUS: Arkistoyksikön nimi kenttä on pakollinen, mutta se on mahdollista tyhjentää massamuokkaamalla

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#178]
**Arkistoyksikön nimi** kentän voi tyhjentää: Aineistohaku | Massamuokkaa valittuja | Tallenna muokatut kentät

**Comment by mustakostaja** [comment]
Ei saa toistettua

**Comment by minna-aaltonen** [comment]
Tämä oli virheellinen vikaraportti.
