### ISSUE TITLE
Tulosta: Toiminto avaa uuden selaimen välilehden ja sulkee sen

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#179]
* Perusnäkymä | Tulosta arkistoluettelo
* ARKISTONMUODOSTAJA | Tulosta
* HÄVITYSEHDOTUS | Tulosta

Tulosta toiminto avaa uuden selaimen välilehden ja sulkee sen ennen järjestelmän tulostusdialogin näyttämistä. Jos on helposti poistettavissa tällainen ominaisuus niin se olisi mukavaa. Ei estä käyttöä. 

Selain: Firefox 37.0.2

**Comment by mustakostaja** [comment]
Ominaisuus, ei korjata.
