### ISSUE TITLE
Hävitysehdotus | Hävitysluettelo: Säilytysyksiköiden lukumäärän laskennassa virhe

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#191]
Kun luon uuden arkistonmuodostajan ja sille arkistoyksikön ja EN laita sitä mihinkään säilytysyksikköön.

-> Hävitysluetteloon tulee säilytysyksiköiden lukumääräksi 0 (oikein) 

Kun luon toisen arkistoyksikön ja lisään molemmat SAMAAN säilytysyksikköön eli nyt minulla on kaksi arkistoyksikköä samassa säilytysyksikkössä.

-> Hävitysluetteloon tulee säilytysyksiköiden lukumääräksi 2 (väärin)

**Comment by mustakostaja** [comment]
Hävitysehdotuksella ei ole säilytysyksiköiden lukumäärää ollenkaan.

**Comment by minna-aaltonen** [comment]
Issuessa puhutaankin hävitysluettelosta, Hävitysehdotus | Hävitysluettelo on polku, jota pitkin navigoidaan hävitysluetteloon.

**Comment by mustakostaja** [comment]
Siistii, korjattu.

**Comment by minna-aaltonen** [comment]
Nyt laskenta menee oikein.
