### ISSUE TITLE
Säilytysyksiköt | Tee haku | Nimiö: Salassapitoaika (vuotta) ja Salassapidon päättymisajankohta puuttuvat nimiöltä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#193]
Jos arkistoyksikön **Julkisuus** kentän arvo on _Salassapidettävä_ tai _Osittain salassapidettävä_, säilytysyksikön nimiössä pitäisi näkyä myös arkistoyksikön:
* **Salassapitoaika (vuotta)**
* **Salassapidon päättymisajankohta**

vrt. Liite 4.5 Raportit ja tulosteet

**Comment by minna-aaltonen** [comment]
Sijoitetaan tiedot nimiön **Julkisuus** kenttään kauttaviivalla toisistaan ja julkisuustiedosta erotettuna.

**Comment by minna-aaltonen** [comment]
* **Julkisuus** kentässä ei ole tekstin rivitys päällä lisätyt tiedot eivät mahdu soluun 
* Näyttää lisätyt tiedot myös, jos **Julkisuus** kentän arvo on _Julkinen_ (ei vaatimuksen mukaan pitäisi).

**Comment by mustakostaja** [comment]
Korjattu niin, että näytetään tiedot ainoastaan jos julkisuus != julkinen.
Rivitystä ei ole käytössä missään kentässä, koska silloin tiedot eivät ainakaan mahdu yhdelle paperille.

**Comment by minna-aaltonen** [comment]
OK, jos salassapidon päättymisajankohta on päivämäärä, se mahtuu hyvin kyllä nimiölle.
Testataan julkisuustiedon näyttö, kun korjaus on QA:lla.

**Comment by minna-aaltonen** [comment]
Nyt näyttää tiedot kuten vaatimuksissa määritelty.
