### ISSUE TITLE
Paula: Raportit | Lainaustilasto: Lainaustilasto järjestäminen puuttuu

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#194]
Lainaustilasto pitäisi järjestää:
vuosittain > arkistonmuodostajittain > sarjoittain > arkistoyksikön määrät

Tällä hetkellä tietoja ei ole järjestetty.

Kts. Liite_4

**Comment by mustakostaja** [comment]
Vaatimuksessa lukee saatava seuraavasti: vuosittain > arkistonmuodostajittain > sarjoittain > arkistoyksikön määrät. Ei ole puhetta sorttauksesta. Tarkistetaan yhdessä.

**Comment by minna-aaltonen** [comment]
Sama juttu koskee myös aineistotilasto raporttia.

**Comment by KelaTest** [comment]
Meidän näkemyksemme mukaan tuo vaatimuksen sanamuoto tarkoittaa nimenomaan myös järjestystä. Muutenhan luettelo on täysin käyttökelvoton. N&P

**Comment by ArnoSaine** [comment]
Järjestetään vuosiluvun mukaan uusin ylimmäksi.
