### ISSUE TITLE
Perusnäkymä | Arkistonmuodostajalista: Jos poistetaan peräkkäin kaksi arkistonmuodostajaa, poisto ei päivity Päänäkymään

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#196]
Näin toistat:
1. Luo kaksi arkistonmuodostajaa
2. Poista ensimmäinen -> OK
3. Poista toinen -> Päänäkymän arkistonmuodostajalista lakkaa päivittymästä ja poistetut arkistonmuodostajat näkyvät edelleen listalla.

Hakusanoja: Päivitys, päivittyminen

**Comment by mustakostaja** [comment]
Ei saada toistettua
