### ISSUE TITLE
Hävitysehdotus | Tee hävitysehdotus: arkistoyksikön poisto aiheuttaa päivittymisongelman Hävitysehdotukset listaan

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#198]
Näin toistat:
* Luo arkistonmuodostaja, jolla on kaksi aineistoa, jotka ovat hävitettävissä
* Poista toinen aineisto
* Hävitysehdotus | Hävitysehdotukset | <valitse yllä käytetty arkistonmuodostaja> | Tee hävitysehdotus

-> Hävitysehdotus ei päivity listaan. Sivu täytyy uudelleenladata, jotta hävitysehdotus tulisi näkyviin.

**Comment by ArnoSaine** [comment]
fixed: f59b7a4
