### ISSUE TITLE
Hävitysehdotus | Tee hävitysehdotus: Hävitysehdotus kustannuspaikan mukaan on tyhjä vaikka pitäisi olla arkistoyksikköjä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#200]
Aiemmin tämä on toiminut, mutta nyt ARTI kustannuspaikan mukaan tehty hävitysluettelo on tyhjä vaikka sinne pitäisi tulla arkistoyksikköjä (aineisto on Hävitettävissä ja sen ARTI kustannuspaikka on sama kuin mitä on valittu Hävitysehdotus sivulla).

**Comment by mustakostaja** [comment]
Korjattu aikaisemmin. Taitaa olla jo testissä.

**Comment by minna-aaltonen** [comment]
Kyllä, nyt näyttää taas toimivan.
