### ISSUE TITLE
IE11: Aineistohaku: Haku kenttien yhdistelmillä ei toimi

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#201]
**Nämä toimivat Firefox selaimella**

Seuraavat hakukenttien yhdistelmät eivät toimi Internet Explorer 11 selaimella:
* Arkistonmuodostaja + Tunnus

Osasanahaku ei toimi ainakaan konversiossa tuoduille aineistoille (ei löydä kentän arvon osalla) kentässä:
* Sarjan lisätiedot 
* Arkistoyksikön nimi
* ARTI nimi

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia; massamuokkauksen kannalta tärkeä haku. (niina&paula)

**Comment by minna-aaltonen** [comment]
Aineistohaku sarjan tunnuksella ei toimi edelleenkään (IE11: aineistohaku ei toimi sarjan tunnuksella #212), joten tämä issue ei ole korjaantunut.

**Comment by minna-aaltonen** [comment]
Nyt aineistohaku kenttien yhdistelmillä toimii.
