### ISSUE TITLE
Arkistoyksiköiden selaus: Vaatimusten mukaan pitäisi selata Ark. yks. järjestysnro:n perusteella

### ISSUE THREAD

**Issue by ArnoSaine** [Proactum/ARTI#205]
Siirtyminen kaavassa edelliseen/seuraavaan sarjaan. Toimii nyt sarjan sisällä.

**Comment by minna-aaltonen** [comment]
Vaatimusexcelissä sanotaan: "Tarkoitetaan arkistoyksikköjen selaamista arkistokaavan hierakian mukaisessa järjestyksessä arkistoyksikön järjestysnumeron mukaisessa järjestyksessä."

Nyt selaus tapahtuu arkistoyksikön ID:n perusteella.

**Comment by minna-aaltonen** [comment]
Tämä toteutus on vaatimusten vastainen, mutta loogisesti järkevä. Nyt selaa arkistoyksikköjä samassa järjestyksessä kuin ne näytetään näytöllä. Palataan tähän, jos asiakkaan mielestä tässä on jotain ongelmaa.

**Comment by minna-aaltonen** [comment]
Asiakkaan näkemys issuessa:  Arkistoyksiköiden selaus #233
