### ISSUE TITLE
Paula: ARKISTOYKSIKKÖ | ARTI kustannuspaikka: kustannuspaikan nimi ei mahdu kenttään kokonaan

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#206]
ARTI kustannuspaikka kentän pituutta pitäisi kasvattaa.

Katsotaan tätä hyväksymistestauksen jälkeen. Vastaavan tyyppisiä korjauksia tulee varmaan lisää ja tehdään niitä sitten kerralla.

**Comment by KelaTest** [comment]
Olemme joo ilmoittaneet muitakin vastaavia. Jos työekonomisesti mahdollista, niin olis tietysti kiva että ne olis jo tuotannossa kunnossa. P&N

**Comment by ArnoSaine** [comment]
Duplicate #86
