### ISSUE TITLE
IE11: aineistohaku ei toimi sarjan tunnuksella

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#212]
Aineistohaku palautta nolla hakutulosta, kun haen sarjan tunnuksella D.c. Testattu IE11:lla. (Paula)

**Comment by minna-aaltonen** [comment]
Toimii Firefox:lla, mutta ei toimi IE11:sta.

Sukua ongelmalle: IE11: Aineistohaku: Haku kenttien yhdistelmillä ei toimi #201

**Comment by minna-aaltonen** [comment]
Ei ole korjaantunut, ei edelleenkään löydä mitään sarjan tunnuksella, jos selaimena on IE11.

**Comment by minna-aaltonen** [comment]
Nyt toimii aineistohaku sarjan tunnuksella.
