### ISSUE TITLE
Perusnäkymä arkistonmuodostajalista

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#213]
Olisiko mahdollista pidentää näkyvää arkistonmuodostajalistanpätkää niin paljon kuin sivun korkeus antaa myöden? Mielestäni tästä ollut puhetta aiemmin. 
(niina)

**Comment by minna-aaltonen** [comment]
Suljetaan duplikaattina issuelle:  Niina: Perusnäkymä: Arkistonmuodostajalistan pitäisi olla pidempi #95
