### ISSUE TITLE
SARJA | Tunnus: virheilmoitus duplikaatista sarjaa siirrettäessä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#216]
"Kokeilen siirtää Da-sarjaa E-sarjan alle siten, että uusi sarja on Ea. Tulee virheilmoitus Oops. (ei pitäisikään voida tehdä kahta samaa kirjainta, mutta ei varmaan pitäisi tulla virheilmoitustakaan?)
Voisiko saada virheilmoituksen seuraavaan: (kopio sposti minna/30.3.)järjestelmä toimii nyt siten, että arkistokaavassa ei voi olla kahta sarjaa, joilla on sama tunnus. Tällä hetkellä tilanteessa ei vielä näytetä virheilmoitusta. Jotain tyyliin Tällaista muutosta ei voi tehdä."
(niina)

**Comment by minna-aaltonen** [comment]
Tuossa siirtotilanteessa ei tule virheilmoitusta lainkaan, sarja ei vain siirry, jos tunnuksista tulisi samat. Pelkästään vastaavalla sarjan siirrolla en saa tuota Oops ilmoitusta toistumaan. Voisitko ystävällisesti tarkistaa toistuuko Oops ilmoitus sinulle aina vastaavassa tilanteessa?

**Comment by minna-aaltonen** [comment]
Jos Oops ei ole toistettavissa, on duplikaatti issuelle: Ei virheilmoitusta kun sarja koitetaan siirtää niin että sen tunnuksesta tulee duplikaatti #73

**Comment by KelaTest** [comment]
Muutin Da sarjaa Ea:ksi. Tallenna napista ei tapahdu mitään. Kun painan toiseen kertaan, ei vieläkään tapahdu mitään. Painelin vielä 5-6 kertaa, ei inahdakaan, mutta ei myöskään tule Oopsia.

**Comment by KelaTest** [comment]
Toivoisimme vastaaviin kaikkiin kohtiin huomautusilmoitusta. Nyt on ärsyttävää, kun jää renkkaamaan jotain jos ei heti tajua, että ei pitäisikään tapahtua mitään.

**Comment by minna-aaltonen** [comment]
OK, kiitos kun testasit! Palataan tähän, jos tuo ongelma saadaan toistettua.

Kyllä tästä tilanteesta pitäisi tulla virheilmoitus, mutta käsitellään se issuessa: Ei virheilmoitusta kun sarja koitetaan siirtää niin että sen tunnuksesta tulee duplikaatti #73. Suljen tämän issuen duplikaattina.
