### ISSUE TITLE
Ei pysty muuttamaan Aa sarjaa A-sarjaksi.

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#217]
Ei pysty muuttamaan Aa sarjaa A-sarjaksi. (pääkäyttäjän tulee voida kirjata pääsarjalle)
(niina)

**Comment by minna-aaltonen** [comment]
Tarkoititko jotain tällaista:
1. Avaa arkistoyksikkö sarjasta A.a
2. Siirrä arkistoyksikkö sarjaan A

Minulla tällainen siirto kyllä onnistui. Ymmärsinköhän oikein mikä oli ongelma?

**Comment by KelaTest** [comment]
Olinpa kirjoittanut huonosti tuon... Nyt kun tarkemmin mietin koko tapausta, niin ei tässä ole mitään ongelmaa. Tän voi klousaa.
