### ISSUE TITLE
Ei pysty muuttamaan pääsarjaa toiseksi pääsarjaksi, jos molemmat olemassaolevia.

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#218]
"Ei pysty muuttamaan pääsarjaa toiseksi pääsarjaksi, jos molemmat olemassaolevia. 
Minna sanoi noin 27.3. huitteilla, ettei sarjojen yhdistämistoimintoa ole; oliko mitään keinoa viedä pääsarjan alaiset toiseen pääsarjaan könttänä? Itse keksin vain sen tavan, että muuttaa pääsarjan toisen pääsarjan alasarjaksi ja sitten käy muuttamassa uudet sarjatunnukset sarjoille ja alasarjoille ja viime kädessä poistaa/muuttaa alku. pääsarjan takaisin (tai sen, että muuttaa kaikki alasarjat yksitellen oikein mutta se saattaa käytännöss sotkea tekemistä). Ohjeeseen: jos ei mahdollista muuttaa pääsarjaa toiseksi pääsarjaa > ohje/et siitä, miten kaikki pääsarjan alla oleva muutetaan toisen pääsarjan alle."
(niina)

**Comment by minna-aaltonen** [comment]
Sarjan arkistoyksiköt voi siirtää massamuokkauksena toisen sarjan alle:
1. Avaa **Aineistohaku** sivu.
2. Valitse **Arkistonmuodostaja**.
3. Kirjoita **Tunnus** kenttään siirrettävän sarjan tunnus.
4. Valitse **Valitse kaikki** valintaruutu ** Hakutulos taulukosta.
5. **Massamuokkaa valittuja**.
6. Arkistonmuodostaja ja sarja: **Vaihda**.
7. Valitse **Arkistonmuodostaja** ja sarjan **Tunnus**, jonka alle arkistoyksiköt siirretään.
8. **Valitse**.
9. **Tallenna muokatut kentät**.

Onko ratkaisu mielestänne ok?

**Comment by minna-aaltonen** [comment]
Huom! Tätä ei voi tällä hetkellä testata IE:llä, korjaus ei ole vielä QA:lla (IE11: aineistohaku ei toimi sarjan tunnuksella #212)

**Comment by KelaTest** [comment]
Miksi on mahdotonta muuttaa esm N > M? Kun kaikkea muuta pystyy suunnilleen muuttamaan? Niina

**Comment by minna-aaltonen** [comment]
Pääsarjan tunnuksen N voi kyllä vaihtaa M:ksi, jos arkistonmuodostajalla ei ole jo sarjaa M. Se ei puolestaan onnistu, että N muutetaan M:ksi, jos M on jo olemassa. Tässä tulee vastaan se rajoite, että samalla arkistonmuodostajalla ei voi olla kahta sarjaa, joilla on sama tunnus.

**Comment by KelaTest** [comment]
Kiitos, Laitatko tuonkin käyttöohjeeseen :)

**Comment by minna-aaltonen** [comment]
Lisäsin käyttöohjeeseen uuden luvun, jossa tämä on kuvattu:
https://github.com/Proactum/ARTI/blob/master/documentation/3.5%20Arkistokaava%20ja%20sarjat.md#sarjojen-tietojen-yhdist%C3%A4minen

Jätän vielä auki, jotta muistan varmasti tarkistaa, että sarjojen yhdistäminen toimii myös IE:llä, kun ollaan saatu nuo liittyvät IE korjaukset tehtyä.

**Comment by minna-aaltonen** [comment]
Pieni tarkennus ohjeeseen tarvittiin:
4. Jos haluat liittää sarjan ja kaikkien sen alasarjojen arkistoyksiköt toiseen sarjaan, valitse **Valitse kaikki** valintaruutu **Hakutulos** taulukosta. Jos haluat siirtää vain valitun tason sarjan arkistoyksiköt, ne on valittava kukin erikseen mukaan massamuokkaukseen klikkaamalla ko. rivin lopussa olevaa valintaruutua.

**Comment by minna-aaltonen** [comment]
Nyt on testattu myös IE:llä ja näyttäisi toimivan hyvin.
