### ISSUE TITLE
Horjuvuutta sarjan tietojen päivittymisessä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#219]
"Horjuvuutta päivittymisessä: 
- Pääsarjan siirto toisen pääsarjan alasarjaksi > tieto ei päivity ilman F5. (Kun muutin päivittyneen tiedon takaisin toisen pääsarjan alasarjasta omaksi pääsarjaksi, muutos tuli heti arkistokaavalle.) 
- Muutetaan sarjoja alasarjoiksi saman pääsarjan sisällä (Muutetaan Be > Baa), ei päivity ilman F5. "
(niina)

**Comment by minna-aaltonen** [comment]
Suljetaan duplikaattina issuelle:  Muutokset sarjojen sijainnissa eivät päivity Arkistonmuodostaja ponnahdusikkunaan #61
