### ISSUE TITLE
Käyttöohjepäivityksiä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#221]
"Olisiko mahdollista saada käyttöohjeeseen muutamia täydennyksiä? 
- sarjan paikan/tunnuksen muuttamiseen yksityiskohtaisemmat ohjeet.  Esimerkiksi ""jos haluat muuttaa pääsarjan pääsarjaksi, tee näin; jos haluat muuttaa alasarjan pääsarjaksi, tee näin; jos haluat muuttaa alasarjan toiseen pääsarjaan, tee näin"" + tiedot siitä, mitä EI voi tehdä. Minna on näitä meille jo sähköpostiin silloin tällöin laittanutkin, kuten: 
-""Tunnus kentässä on kahdenlaisia painikkeita: Sarjojen tunnukset ja >. Jos haluat esim. siirtää alasarjan toisen arkistonmuodostajan pääsarjaksi, saat asetettua oikean tunnuksen klikkaamalla Tunnus kentässä pääsarjan tunnusta ja valitsemalla valikosta ""> Sijoita sarja tälle tasolle"". Kannattaa vielä kokeilla tätä. Kunhan käyttöön tottuu, toiminta on itse asiassa todella kätevä. Aluksi voi olla vain hankala keksiä, että myös sarjan tunnus on painonappi."" JA
- pääsarjan siirtoa arkistonmuodostajalta toiselle.
1) Loin uuden arkistonmuodostajan (nimi: Minnan), jolla ei ole arkistokaavaa lainkaan
2) Otin arkistonmuodostaja Kenttäosastolta (päättynyt arkistonmuodostaja) pääsarjan ja siirsin sen Minnalle
    -> Päänäkymässä klikkaa arkistonmuodostajan nimen vierestä (Kenttäosasto) - Arkistonmuodostaja ponnahdusikkuna aukeaa
    -> Klikkaa siirrettävän pääsarjan nimeä - Sarja ponnahdusikkuna aukeaa
    -> Valitse uusi arkistonmuodostaja (Minnan)
    -> Tallenna
    -> Palaa
3) Avaa arkistonmuodostaja, jolle sarja on siirretty (Minnan)
    -> Päänäkymässä klikkaa arkistonmuodostajan nimen vierestä (Kenttäosasto) - Arkistonmuodostaja ponnahdusikkuna aukeaa
    -> Pääsarja on siirtynyt arkistonmuodostajalta toiselle. 

Tämän myös voisi lisätä: 
- ohjeeseen (muotoillen): järjestelmä toimii nyt siten, että arkistokaavassa ei voi olla kahta sarjaa, joilla on sama tunnus. jos haluat siirtää sarjan toiseen pääsarjaan, jossa on jo samanniminentunnuksinen alasarja, tulee (väliaikaisesti) uudelleennimetä jompi kumpi sarjaTUNNUS ja poistaa ylimääräinen sarja siirron jälkeen. 

Ylipäätään käyttöohjeeseen olisi hyvä laittaa sellaiset toimintatavalliset asiat, joista olemme projektin kuluessalennossa sopineet, mutta joistaei muita kirjauksia taida olla olemassa. Esimerkiksi hauissa se sarjan tunnusjuttu, että jos hakee Sarjan tunnuksella Bc niin saa sen ja kaikki sen alasarjat jne. 
Olisi myös hyvä, jos siellä olisi tieto asioista, joita järjestelmässä ei voi tehdä. En nyt osaa antaa näistä viimeisistä sen ihmeempiä esimerkkejä, kahlaan käyttöohjeen vähän myöhemmin kokonaisuutena.
"
(niina)

**Comment by minna-aaltonen** [comment]
Muokattu käyttöohjeesta kohta: https://github.com/Proactum/ARTI/blob/master/documentation/3.5%20Arkisto.md#muuta-sarjan-tietoja

Aineistohauissa on Niinan mainitsema sarjan tunnusjuttu jo kuvattu: https://github.com/Proactum/ARTI/blob/master/documentation/2.1%20Aineistojen%20hakeminen.md#hakukriteerit
