### ISSUE TITLE
Eheys/tietokortin varaaminen

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#223]
EHEYS/tietokortin 'varaaminen' (vaatimus 2.2.), ongelma punaisella: Niina ja paula avaavat saman kortin, niina eka. Paula tekee muutoksen ja tallentaa. Niina saa heti ilmoituksen, tiedot eivät ole muuttuneet niinalla, niina kuittaa ok. Painikkeet on kaikki harmaana. Paula jää näytölle. Niina sulkee kortin. Niina avaa kortin uudestaan; tiedot on päivittyneet, tallenna-painikkeet on "aktiivisia". niina tekee muutoksen ja painaa "tallenna". muutos näkyy heti paulalla, mutta paula ei saa ilmoitusta. paula tekee muutoksen ja tallentaa; muutos ei näy niinalla, mutta tulee ilmoitus. 
(niina&paula)

**Comment by minna-aaltonen** [comment]
Tietokortin yhtäaikainen päivittäminen tapahtuu seuraavasti: 
* Kahdella käyttäjällä voi olla sama kortti avoinna.
* Jos toinen käyttäjä ei koske kortin sisältöön ja toinen muuttaa kortin sisältöä, korttia katselleen näyttö päivittyy ja muutoksista ei tule virheilmoitusta.
* Jos molemmat käyttäjät muuttavat kortin sisältöä, ensiksi muutoksen tallentaneen muutokset menevät läpi ja toinen saa heti ilmoituksen: _"Lomakkeen tietoja on muutettu muualla. Tekemiäsi muutoksia ei voida tallentaa. Ole hyvä ja ota tekemäsi muutokset talteen esimerkiksi leikepöydälle, ja avaa lomake uudelleen."_. Toinen joutuu lataamaan kortin uudelleen voidakseen tehdä omat muokkauksensa.
* Tällä hetkellä **Tallenna** napin toiminnassa on vika ja kortit aukeavat siinä tilassa kuin niitä olisi muutettu, joten käyttökokemus (milloin virheilmoitus tulee) ei ole ihan looginen. (Tämä liittyy issueen:  Paula: Tallenna napin pitäisi olla inaktiivinen, kun lomake avataan #127) 

Yhteenvetona: Meidän mielestämme tämä toiminnallisuus toimii kuten olemme suunnitelleet ja tietojen eheys ei ole vaarassa. Nyt kysymys kuuluukin onko tämä toiminnallisuus teidän mielestänne ok (sitten kun saadaan tuo **Tallenna** napin toiminta korjattua)?

**Comment by KelaTest** [comment]
niina&paula: 
keskustelimme pitkään ja hartaasti asiasta ja totesimme, että on ok.

**Comment by minna-aaltonen** [comment]
Jätän tämän auki ja testataan huolella toiminta sitten kun issue Paula: Tallenna napin pitäisi olla inaktiivinen, kun lomake avataan #127 on korjattu.

Lisäsin tiedon päivittymisestä käyttöohjeeseen: https://github.com/Proactum/ARTI/blob/master/documentation/1.5%20J%C3%A4rjestelm%C3%A4n%20yht%C3%A4aikainen%20k%C3%A4ytt%C3%B6.md
