### ISSUE TITLE
Kaikkien metatietokenttien tiedot pitäisi näkyä automaattisesti kokonaisuudessaan

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#224]
En muista (viitsi etsiä) onko tästä jo jotain auki, mutta olemme mielestäni sopineet,että poistamme metatietokenttien scrollbarit (esimerkkinä arkmu kuvailu). Se "kulmavenyke" voi olla; parhaimmana pitäisimme, että kaikki kentässä oleva teksti näkyisi automaattisesti kokonaisuudessaan. 
(niina)

**Comment by ArnoSaine** [comment]
Duplicate #86
