### ISSUE TITLE
Perusnäkymä | Näytä: Arkistonmuodostajavalikossa näytetään väärät arkistonmuodostajat aktiivisina ja päättyneinä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#226]
"Arkistonmuodostaja-valikko: Ohjeessa ja toteutuksessa virhe. Säännön pitää olla seuraavasti:Näytä alasvetovalikon valinnat:
•Aktiiviset: Arkistonmuodostajan nimi näytetään arkistonmuodostajien listassa, jos sen Arkistonmuodostajan rajavuodet tiedon päätösvuosi on tyhjä. 
•Päättyneet: Arkistonmuodostajan nimi näytetään arkistonmuodostajien listassa, jos sen Arkistonmuodostajan rajavuodet tiedon päätösvuosi on annettu.
"
(paula)

**Comment by minna-aaltonen** [comment]
Näin on määrittelyn tarkennuksissakin pyydetty tekemään.

**Comment by mustakostaja** [comment]
Eli tämä ongelma siis koskee ohjeita?  Toteutus on nyt ainakin seuraava:
aktiiviset: tyhjät tai jos loppuvuosi on suurempi  tai yhtäsuuri kuin kuluva vuosi
päättyneet: jos loppuvuosi on pienempi kuin kuluva vuosi

**Comment by minna-aaltonen** [comment]
Koskee toteutusta. Ohje on toteutuksen mukainen, ohjetta pitää korjata, kun toteutus on korjattu.
