### ISSUE TITLE
Tallenna-painikkeiden toiminnallisuudet

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#227]
Kun avaa olemassaolevan arkistoyksikön, tallenna-namiska on aktiivi-sinisenä. Pitäisi olla harmaa niin kauan kunnes jokin tieto muutettu, kuten kaikissa muissa yhteyksissä.
(niina&paula)

**Comment by minna-aaltonen** [comment]
Suljetaan duplikaattina issuelle:  Paula: Tallenna napin pitäisi olla inaktiivinen, kun lomake avataan #127
