### ISSUE TITLE
ARKISTOYKSIKKÖ | Rajavuodet: Rajavuosikenttiin voi tallentaa kirjaimia

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#229]
Kirjasin uuden arkistoyksikön rajavuosi-kenttiin  1jklö   ja 2fadfas. Tallennus onnistui,  vaikka ei olisi pitänyt.

**Comment by minna-aaltonen** [comment]
Nyt ei väärän muotoista tietoa pysty tallentamaan.
