### ISSUE TITLE
ARKISTOYKSIKKÖ: Arkistoyksikön tallenna ja kopioi -toiminnossa virheitä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#230]
ID:135053. Avasin aiemmin tallennetun arkistoyksikön 135053. En tehnyt muutoksia. Tallenna ja kopioi- painikkeella kopioidussa arkistoyksikössä rajavuodet ja ark.yks.järjestysnumero puuttuvat.  Lisää -näppäin ei muutu aktiiviseksi, vaikka käpälöin tietoja. (Paula). 

 Kuvaruutukaappaus liitteenä
![virhe6a](https://cloud.githubusercontent.com/assets/11074411/7830834/9300b216-0459-11e5-9504-2cdf39313bac.PNG)
![virhe6b](https://cloud.githubusercontent.com/assets/11074411/7830840/9da4cf72-0459-11e5-8017-71b6e5914250.PNG)

**Comment by minna-aaltonen** [comment]
**Tallenna ja kopioi- painikkeella kopioidussa arkistoyksikössä rajavuodet ja ark.yks.järjestysnumero puuttuvat.**
* Toimii kuten määritelty (Liite 4.4 Metatiedot, sarake N)

**Lisää -näppäin ei muutu aktiiviseksi**
* Tämä on ongelma: Kopioitua korttia ei voi tallentaa.

**Comment by KelaTest** [comment]
Olimme ymmärtäneet niin, että muutettiin kohtaa siten että kaikki tiedot kopioidaan. On hyvä niin että pysytään alkuperäisessä määrittelyssä ja rajavuodet ja arkistoyksikön järjestysnumero eivät kopioidu. Voisitteko lisätä maininnan tästä käyttöohjeeseen.  
Lisää-näppäimen aktivointi-ongelma on tosiaan aika häiritsevä, toivon korjausta ensi tilassa!

**Comment by minna-aaltonen** [comment]
Maininta kenttien poikkeuskäsittelystä lisätty käyttöohjeeseen: https://github.com/Proactum/ARTI/blob/master/documentation/3.1%20Arkistoyksikk%C3%B6.md#tallenna-ja-kopioi-arkistoyksikk%C3%B6

Yritettään saada Lisää nappi toimimaan mahdollisimman pian.

**Comment by minna-aaltonen** [comment]
Lisää napin toiminnasta on jo toinen issue, suljen tämän duplikaattina, kts.  ARKISTOYKSIKKÖ | Tallenna ja kopioi: Uutta arkistoyksikköä ei voi tallentaa #210
