### ISSUE TITLE
Hävitysehdotus | Tee hävitysehdotus: Hävitysehdotuslista ei päivity luotettavasti

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#232]
Hävitysehdotuksen muodostaminen ei onnistu. Valitsen osaston, painan "tee hävitysehdotus". Nappi on sinisenä pistereunoin, mitään ei tapahdu. Toimintoa ei pysty testaamaan. (niina)

**Comment by KelaTest** [comment]
F5 jälkeen löytyy kolme hävitysehdotusta (tulin painaneeksi "tee"-nappia kokeeksi useamman kerran.

**Comment by KelaTest** [comment]
valitessani uuden arkistonmuodostajan ehdotus tulee normaalisti, pienellä viiveellä. Oli joku ohimenevä F5-virhe?

**Comment by minna-aaltonen** [comment]
En pysty toistamaan ongelmaa, F5 virhe on hyvä arvaus. Tämän voisi sulkea ja avataan uudelleen, jos ongelma toistuu?

**Comment by KelaTest** [comment]
Jep, kokeilen jossain vaiheessa uudestaan.

**Comment by KelaTest** [comment]
Kokeilin kustannuspaikan mukaista hävitysehdotusta. Sama juttu, luetteloa ei tule valikkoon, F5 korjaa tilanteen.

**Comment by KelaTest** [comment]
Se tekee sen jopa niin, että f5 tehdään vain ensimmäisen kerran, sen jälkeen kaikki aukeaa normaalisti listaan ilman f5ttä.

**Comment by minna-aaltonen** [comment]
En pysty edelleenkään toistamaan vikaa.

Testasin IE 11.0.9600.17239 ja 11.0.9600.17801 versioilla.

1. Tyhjensin kaiken historiatiedon Internet Options:sta 
2. Annoin demo tunnukset
3. Kirjauduin ARTI:n pääkäyttäjänä (koitin samaa myös peruskäyttäjänä)
4. Valitsin Hävitysehdotus | Kustannuspaikka | AKTUAARI- JA TILASTO-OSASTO 

-> Hävitysehdotus ilmestyi heti listalle

Meidän on vähän hankalaa päästä ongelmaan käsiksi, jos emme saa sitä toistetua täällä.

**Comment by KelaTest** [comment]
Pystyn edelleen toistamaan virheen. Pyydän Paulaa toistamaan tämän myös huomenna. Ja myös sen Arkistonmuodostaja-virheen, niin katsotaan onko kone/tekijäkohtaista. niina

**Comment by KelaTest** [comment]
Toistin testauksen siten, että tyhjensin kaiken historiatiedon selaimesta. Kirjauduin ulos selaimesta, suljin koneen, tulin normisti takaisin kantaan ja nyt toimii ok. (niina)

**Comment by KelaTest** [comment]
Tein hävitysehdotuksen sekä arkistonmuodostajalla että kustannuspaikalla. Ei näkynyt listalla, vaan  toimi kuten Niina aluksi kuvasi. Kun käväisin toisella välilehdellä, ilmestyi heti näkyviin. Tyhjensin välimuistin ja kirjauduin ulos ja uudestaan sisään, edelleen sama virhe. Kun painoin F5, alkoi toimia heti ok. (Paula).

**Comment by minna-aaltonen** [comment]
Kiitos kovasti avusta! Selvästi nyt jotain vikaa tuossa hävitysehdotuslistan päivittymisessä on. Josko Arno tutkisi voisiko siihen tehdä jotain parannusta, joka tekisi päivittymisestä luotettavamman?

**Comment by KelaTest** [comment]
Pystyn edelleen toistamaan päivittymisvirheen. Kun luon hävitysehdotuksen, se ei ilmesty näkyviin, ennen kuin painan F5. 
Koetin kahdella tavalla: 
Kirjauduin testikantaan. Menin hävitysehdotus välilehdelle. Valitsin alasvetovalikosta arkitonmuodostajan ja valitsin Tee hävitysehdotus. Odotin varmuuden vuoksi pari minsaa. Ehdotus ei ilmestynyt näytölle ennen kuin painoin F5. Tein ehti perään uuden ehdotuksen samalla systeemillä; nyt se ilmestyi heti näkyviin. 
Sitten kirjauduin ulos ja takaisin sisään testikantaan. tein samalla systeemillä hävitysehdotuksen, taas se ilmestyi näkyviin vasta kun painoin F5. 
Vaikuttaa, että ainakin uusissa istunnoissa pitää ensin painaa F5, sitten toimii kuten pitää. Kokeilin, että käyn välillä toisella välilehdellä tekemässä jotain muuta ja tulin sitten taas hävityslehdelle tekemään ehdotuksen; ilmeisesti edellinen freesaus pitää edelleen, koska uusi häv ehdotus tuli normaalisti näkyviin.
(niina)
