### ISSUE TITLE
Arkistoyksiköiden selaus 

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#233]
Arkistoyksiköiden selaus toimii nyt siten, että kun sarjan arkistoyksiköt on selattu loppuun, jatkaa uudestaan sarjan ensimmäisestä. Pitäisi toimia niin, että selaa arkistonmuodostajan kaikki sarjat läpi, siinä järjestyksessä kun ovat perusnäkymässäkin. Viimeisen jälkeen selaus päättyy eikä aloita ensimmäisestä uudelleen (vaatimus 4.4) (Paula)

**Comment by minna-aaltonen** [comment]
Tämä virhe on jo korjattu, mutta korjausta ei ole QA:lla olevassa versiossa.

**Comment by minna-aaltonen** [comment]
Peruutus ei toimi ihan oikein. 

Loin aineistot sarjoille:
A
A.a
A.a.a
A.a.b
A.b
B

Muuten toimii oikein, mutta ei osaa peruutella ylöspäin sarjoista
A.a.a
A.a
A

Sarjat tuotannossa arkistonmuodostajalla öö - Minnan testi
