### ISSUE TITLE
IE11: Säilytysyksikön leveyden tarkistus, tyhjentää varoittamatta ei-numeerisen arvon tallennuksen yhteydessä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#234]
Jos kirjaa säilytysyksikön leveyskenttään (vahingossa) kirjaimia ja painaa tallenna-näppäintä,  leveystieto jää vain tallentumatta ilman mitään vinkkiä että on virheellistä tietoa

**Comment by minna-aaltonen** [comment]
Tiedossa oleva ongelma, liittyy issueen:
* Paula: IE11: Numerokenttien validointi ei toimi #144

**Comment by KelaTest** [comment]
Olisi hyvä tarkistaa myös luvun suuruusluokka, ettei vahingossa pääse kirjaamaan puppua. Tarjouspyynnön määrityksissä on esitetty, että kentän muoto olisi numeerinen ja pituus 3. Eli voisiko tarkistaa, että leveys on  <= 999
