### ISSUE TITLE
Arkistoluettelo, muotokommentit

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#235]
Arkistoluettelosta puuttuu joitain metatietoja. (Nyt olisi sarakeotsikoilla käyttöä. Huomasimme taannoin että emme laittaneet malliin emmekä siksi niitä pyytäneet tekemään, nyt niitä tarttis... )
No, nyt en ole ihan varma mitä tietoa loppupään sarakkeisiin J, K, M ja N tulisi nousta, koska osa noista jää aina tyhjäksi. 
Joka tapauksessa G-sarake on väärässä paikassa, sen tulisi olla viimeisenä, sijaintitiedon oikealla puolella (sarakkeessa M). 
Säilytysaikakentän (sarake I) oikealla puolella tulisi olla Julkisuus, Salassapitoaika, Salassapidon päättyminen, Henkilötieto, Säilytysyksikön jnro; näiden jälkeen Sijainti. Nyt kuitenkin säilytysajan ja sijainnin välissä vain kaksi saraketta. 
Saraketta N ei sinänsä tarvita (ku en nyt tiedä mitä sinne nousis os olis arvoja), säilytysajan jälkeen tulee vain lisätieto-kenttä (M), johon nousee arkistoyksikön lisätiedot sekä aineistoviitteet. 
Sarjan vastaavat lisätieto+aineistoviitetiedot puuttuu sarjoilta? Pitää etsiä esimerkkimatskua ja testata, tutkin tätä viimemainittua vielä.
Arkyksjnro (D-sarakkeen) leveys voisi olla max 4 merkkiä. Kentän tulisi siis sijaita A-sarakkeena, kuten aiemmin on ollut puhetta. 
arkistoluettelon, kuten muidenkin luetteloiden, tulisi automaattisesti mahtua leveydeltään yhdelle vaakasuuntaiselle arkille kaikki sarakkeet yhteen sivuun; olisiko mahdollista siellä päässä lisätä nämä asetukset?

**Comment by minna-aaltonen** [comment]
Arkistoluettelon kunnollinen kuvaus puuttuikin käyttöohjeesta. Lisäsin sarakkeisiin tulevat tiedot käyttöohjeeseen: https://github.com/Proactum/ARTI/blob/master/documentation/4.1%20Arkistoluettelo.md#arkistoluettelon-tiedot

Katsotteko vielä tarkemmin mitkä yllä olevista kommenteista ovat vielä valideja nyt kun on toivottavasti selvempää mitä tietoja Excelissä pitäisi olla.

Arkistoluettelon kentät ovat meidän parhaan ymmärryksemme mukaan vaatimusten mukaisia.

**Comment by KelaTest** [comment]
Kiitos, hyvä lisäys käyttöohjeeseen. 

Sarakkeiden sijaintien tulee olla (näitä käsitelty mallin kera sähköpostikeskustelussa 14.4.2015_Arkistoluettelomalli) :
A: arkistoyksikön Ark. yks. järjestysnro 
B: Arkistoyksikön laatu/säilytysyksikön laatu HUOM, Tähän siis molemmat. Tiedot voidaan erottaa kauttaviivalla (/) (vaat. s. 4.4).
C: arkistoyksikön Ala-arkistonmuodostaja
D: Arkistoyksikön nimi
E: arkistoyksikön Nimen tarkenne
F: arkistoyksikön Rajavuodet, tarkenne tai jos tietoa ei ole annettu, arkistoyksikön Rajavuodet
G: arkistoyksikön Säilytysaika (vuotta) tai Säilytysaika (muu arvo), jos Tulostettava aineisto on Muu arvo tai Kaikki.
H: arkistoyksikön Julkisuus
I: arkistoyksikön Salassapitoaika (vuotta), jos arkistoyksikön Julkisuus on Salassapidettävä tai Osittain salassapidettävä.
J: arkistoyksikön Salassapidon päättymisajankohta, jos arkistoyksikön Julkisuus on Salassapidettävä tai Osittain salassapidettävä.
K: arkistoyksikön Henkilötieto
L: säilytysyksikön Numero 
M: arkistoyksikön säilytysyksikön Sijainti
N: arkistoyksikön sarjan Aineistoviite SARJALLE PITÄISI VIELÄ OLLA SARJAN LISÄTIETO-METATIETO, arkistoyksikön Näyte, otanta ja arkistoyksikön Aineistoviite PITÄISI OLLA VIELÄ ARKISTOYKSIKÖN LISÄTIETO-METATIETO

Lisäksi Sarjan lisätiedot ei saa näkyä arkistoyksiköllä, vaan tuleen näkyä sarjan rivillä sarakkeessa N.

Jotta saadaan muu tila maksimaalisesti käyttöön, Arkyksjnro (A-sarakkeen) leveys voisi olla max 4 merkkiä. Sen säästyneen tilan voisi hyödyntää NIMI-sarakkeessa (D)

Arkistoluettelon, kuten muidenkin luetteloiden, tulisi automaattisesti mahtua leveydeltään yhdelle vaakasuuntaiselle arkille kaikki sarakkeet yhteen sivuun; olisiko mahdollista siellä päässä lisätä nämä asetukset?

**Comment by KelaTest** [comment]
Jos tämä ei jo tullut vielä esille, niin arkistoluettelon tiedot eivät rivity.

**Comment by minna-aaltonen** [comment]
Vastauksesta en löytänyt poikeamaa vaatimusksista.

**Comment by KelaTest** [comment]
Sarjan tietoja ei voi ilmoittaa arkistoyksikön kohdalla, tieto ei tällöin ole validia eivätkö luettelot käyttökelpoisia, ts. oikeatietoisia.
Kelan näkökulmasta toimittaja ei voi vedota määrittelyjen puutteeseen, koska määrittelyjä tuli tarkentaa ketterästi toteutusvaiheen aikana; toimituksen myöhästyessä tarkennuksiin ei koskaan toimittajan toimesta päästy.
Kela katsoo, että arkistoluettelon muotoiluun liittyvä määrittelyn tarkennus on kuvattu yllä toteutusvaiheen aikana ja tulee toteuttaa.

**Comment by KelaTest** [comment]
Luettelo näyttäisi muuten olevan kunnossa, kiitos mutta; 
-	olisiko vielä mahdollista erotella lisätietokenttään nousevat, eri kentistä periytyvät tiedot vaikka kautta-viivalla, kuten sarjan tiedoissa!?
-	Sarakejärjestys: oli hyvä idis laittaa lisätiedot viimeiseksi; muilta osin toivoisin, että sarakejärjestys palautettaisiin samaksi kuin se oli edellisessä versiossa
