### ISSUE TITLE
Hävitysehdotus: hävitysehdotuksen muuttuminen hävitysluetteloksi

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#236]
Tämä on ollut jo pitkin matkaa. Kun hyväksyn hävitysehdotuksen (paljon tavaraa), hävitysehdotus muuttuu tallennuksen aikana suoraan hävitysluetteloksi namiskoineen kaikkineen. Oli hyvin aikaa painaa Tulosta hävitysluettelo"-nappia, ja luettelo tulostui tiedostoon. Kun ehdotuksen tallennus meni loppuun, popup poistui normaalisti. Hävitysluettelo-lehdellä piti silti vielä erikseen painaa tulosta-nappia, eli vaikka ehdin tulostaa luettelon ihan väärässä paikassa/vaiheessa, siitä ei jäänyt mitään rekisteriin enkä päässyt suoraan hävittämään mitään.

**Comment by minna-aaltonen** [comment]
Nyt hävitysehdotus sulkeutuu eikä muutu hävitysluetteloksi vaikka siinä olisi paljonkin aineistoja. Tietojen tallentuminen kestää jonkin aikaa ja kestää hetken ennen kuin hävitysehdotus siirtyy **Hävitysehdotukset** välilehdeltä **Hävitysluettelo** välilehdelle.
