### ISSUE TITLE
Perusnäkymä | Avaa kaikki sarjat: Avaa koko sarja -painike avaa arkistoyksiköt näkyviin

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#237]
Tein oman arkistonmuodostajan 'Paulan', ja sinne arkistoyksiköitä. Avaa koko sarja -painike käyttäytyy tässä eri tavalla kuin muilla (konvertoiduilla?) arkistonmuodostajilla ja avaa arkistoyksikötkin näkyviin.

**Comment by minna-aaltonen** [comment]
Arkistonmuodostaja Paulan pääsarjan A alla on sekä alasarja A.a (aihe avata sarja A) että arkistoyksiköitä. Se ei kuitenkaan (ainakaan minulla IE11) avaa sarjaa A.a, koska sen alla on vain arkistoyksiköitä. **Avaa kaikki sarjat** avaa siis kaikki sarjat, joiden alla on alasarjoja, mutta ei avaa sarjoja, joiden alla on vain arkistoyksiköitä. Onko toiminnallisuus ok?

**Comment by KelaTest** [comment]
On ok.

**Comment by minna-aaltonen** [comment]
Asia lienee tällä selvä, joten suljen issuen.
