### ISSUE TITLE
IE11: Kustannuspaikan mukaisessa hävitysehdotuksessa ongelma

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#238]
Kustannuspaikan mukaiseen hävitysehdotukseen ei nouse aineistoja, vaikka pitäisi. Tämä koskee ainakin kustannuspaikkoja Maksupalveluryhmä, Kirjanpito- ja maksuliikenneryhmä sekä Ulkomaanyksikkö. 
Kävin muuttamassa kp VALTUUTETUT säilytysaikoja. Tämä kp-hävitysehdotus tulee normaalisti. 
Paula hoksasi, että virhe saattaisi johtua siitä, että noissa ensin mainituissa kp-nimissä on ä-kirjain. (niina)

**Comment by minna-aaltonen** [comment]
Ongelma toistettavissa IE 11.0 selaimella. Skandimerkit näyttävät aiheuttavan ongelman.

**Comment by minna-aaltonen** [comment]
Nyt onnistuu hävitysehdotusten teko vaikka kustannuspaikan nimessä olisi skandimerkkejä.
