### ISSUE TITLE
SARJA: Sarjan nimen pitää olla pakollinen

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#240]
Nyt pystyy kirjaamaan sarjan ilman nimeä.(Paula)

**Comment by minna-aaltonen** [comment]
Vaatimusmäärittelyn mukaan pääsarjan nimi on pakollinen, mutta alasarjan voi kirjata ilman nimeä. Haluatteko, että nimi on pakollinen myös alasarjalle?

**Comment by KelaTest** [comment]
Pääsarjan pakollisuus riittää (niina)

**Comment by minna-aaltonen** [comment]
Määrittelyissä vaaditaan, että pääsarjan nimen pitäisi olla pakollinen.

**Comment by KelaTest** [comment]
täsmennän, että pääsarjan ja sarjan nimi ja tunnus on pakollinen, alasarjojen nimet ei tarvitse olla pakollinen.
(sarjahierarkia: 
A = Pääsarja
Aa = Sarja 
Aaa jne = alasarja)
(niina)

**Comment by KelaTest** [comment]
tämä siis vaatimusdokkarissa. (N)

**Comment by minna-aaltonen** [comment]
Totta, kiitos tarkennuksesta.

**Comment by KelaTest** [comment]
Haluamme. Päästään vähemmällä muistamisella :)

**Comment by minna-aaltonen** [comment]
Asia selvä, kiitos tiedosta!

**Comment by mustakostaja** [comment]
Muokattu niin, että pääsarjalla ja sarjalla nimi-kenttä on pakollinen tieto. Eli:
A -> nimi pakollinen
A.a -> nimi pakollinen
A.a.a -> nimi ei ole pakollinen

tunnus on kaikilla sarjatasoilla pakollinen.
