### ISSUE TITLE
Hävitysluettelo, muotokommentit

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#242]
- Hävitysluettelolle ei kuulu nousta arkistonmuodostajan kuvailu (korjattu)
- Rivien arvot eivät rivity
- Luettelon sarakkeiden järjestys tulee olla: (korjattu)
A.	Arkistoyksikön jno
B.	Arkistoyksikön laatu
C.	Ala-arkistonmuodostaja
D.	Arkyks nimi
E.	Arkyks nimen tarkenne
F.	Rajavuodet
G.	Julkisuus 
H.	Henkilötieto
I.	Säilytysyksikön numero
(niina)

**Comment by KelaTest** [comment]
Saisiko hävitysluettelosta ja -ehdotuksesta myös käyttöohjeeseen tiedot samalla tavalla kuin arkistoluettelosta oli, kiitos!

**Comment by KelaTest** [comment]
Olisiko mahdollista saada kaikkiin luetteloihin aputekstit arkistoyksiköiden leveyden ja säilytysyksiköiden määrän perään? Tuntuu, että laitoinkin tästä jo jotain, en vain löydä sitä issueista. Eli että säilyks lkm:n perässä vois lukea "kpl" tai "säilytysyksikköä" tms, ja arkistoyksiköiden leveyksien perässä "hm" (=hyllymetriä). niina

**Comment by minna-aaltonen** [comment]
Käyttöohjeesta löytyykin jo pyydetyt tiedot: https://github.com/Proactum/ARTI/blob/master/documentation/3.3%20H%C3%A4vitysehdotus%20ja%20h%C3%A4vitysluettelo.md

**Comment by mustakostaja** [comment]
Poistettu arkistonmuodostajan kuvailu, muokattu järjestys ja lisätty kpl säilytysyksiköiden määrän perään.
