### ISSUE TITLE
Peruskäyttäjä ei pääse luomaan arkistoyksikköä tyhjältä pohjalta

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#243]
Arkistonmuodostajaa pääse valitsemaan. (Paula)

**Comment by minna-aaltonen** [comment]
Tästä on jo issue:  Perusnäkymä | Luo arkistoyksikkö nappi: Arkistoyksikön luonti ei toimi peruskäyttäjälle, ei voi valita arkistonmuodostajaa ja sarjaa #203 

Suljen tämän issuen duplikaattina.
