### ISSUE TITLE
Raportit | Näytä aineistotilasto: raportin muotoilu & tietojen hakukriteerit

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#246]
Aineistotilaston ajatus on tarjota meille kokonaisnäkemys kaikesta arkistossa olevasta aineistosta. Raporttiin nousee nyt vain kuluva vuosi. Tarkoitus on saada tilastotietoa koko kela-arkiston aineistosta. 
Raportista ei muistaakseni missään välissä ole keskusteltu sen enempää, joten tehdään se nyt. Sääntö on määrittelyissä "2vuosittain > arkistonmuodostajittain > sarjoittain > arkistoyksikön määrät "+ omana tietona "kaikkien arkistoyksiköiden kokonaismäärä hyllymetreinä". 

Nyt tuloksena siis vain kuluvan vuoden aineisto. Haku on lisäksi ylläriylläri erittäin raskas ja jumiutuu/jumiuttaa koneen joka kerta (tällä hetkellä tehnyt sitä puoli tuntia eikä ole näköpiirissäkään että valmistuisi vielä pitkän aikaan; eilen sama juttu). (voihan olla että ne muutkin vuodet [vuoteen 1938] tulevat sieltä vielä, mutta...) 

Voitaisiinko reerata tätä raporttia niin, että uusi sääntö olisi: Arkistonmuodostajittain, pääsarjoittain, arkistoyksiköiden määrät kaikilta toimintavuosilta yhteensä (vuotta ei siis erikseen ilmoitettaisi millään rivillä). Lisäksi lopussa näkyviin koko kela-arkiston aineistojen yhteinen määrä. Ja sääntö oli siis hierarkkinen, eli ensin arkistonmuodostaja, sen alla pääsarjat, joiden kaikkien olemassa olevien vuosien arkistoyksikköjen kpl- ja metrimäärä ilmoitetaan. Esittämistapa voi kyllä hyvin olla riveillä kuten nyt, eli ei mitään näkymähierarkiaa tarvitse rakentaa (paitsi jos haluaa :) Arkistonmuodostajasta voisi olla sen kokonaismetrimäärä + lopun koko arkiston kokonaiskpl- ja metrimäärä.
(niina)

**Comment by minna-aaltonen** [comment]
Suorituskykyongelmasta luotu erillinen issue:
Raportit | Näytä aineistotilasto: Aineistotilasto ei päivity näytölle lainkaan ja jumittaa selaimen #259 

Tällä hetkellä kaikki konversiossa järjestelmään tuodut aineistot saavat vuosiluvukseen 2015. Jos tämä ei ole oikein, mikä vuosiluku aineistoon pitäisi konversiossa liittää?

**Comment by KelaTest** [comment]
Alkuperäinen määritys oli "vuosittain" eli kaikki vuodet. Pelkästään tuo yksi vuosi tukkii koko järjestelmän. 
Raportin pihvi on, että tämä on ainoa paikka, jossa saamme kokonaiskäsityksen kelan arkistoaineistojen määristä, koska tässä järjestelmässä ei ole tilanhallintaa (kuten vanhassa). Tarkoituksena oli saada aineiston määrä vuosittain, arkistonmuodostajittain, sarjoittain, arkistoyksiköittäin, mainitussa hierarkiassa. Raportti olisi kevyempi, jos se tehtäisiin kuten yllä kuvattiin, eli unohdetaan vuosittainen listaus (luettelosta tulisi aivan järjettömän pitkä) ja tehdään arkistonmuodostajittain kaikista sen toimintavuosista ja ei ihan jokaisesta sarjasta vaan esim. pääsarjatasosta, joka tilastointia varten on varsin riittävä. 

Auttoiko tämä?
niina
