### ISSUE TITLE
aineiston hakutulosten näyttäminen & massamuokkauskentät

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#247]
Aineiston hakutuloksista puuttuu edelleen arkistonmuodostaja- ja sarjan nimi&tunnus-tiedot sekä arkistoyksikön jno. Näyttäminen pitää muutoin olla normaalissa perusnäkymän mukaisessa hierakiassa (nykyisten tietojen sarakejärjestys on ok).

Tämä liittyy issue 172:een, mutta teen siihen tarkennuksen. 

Kun hakutulokset näytetään, tulisi ensin näkyä Arkistonmuodostaja, Sarjan tunnus&nimi, Arkistoyksikön jno ja sitten siinä järjestyksessä kuin nyt on; nämä ovat mielestämme kiireellisiä, koska vaikuttavat moneen perusasiaan/-hakemiseen.

Sitten ne muut tiedot, jotka jäävät scrollin taakse oikealle, eivät ole niin kiireellisiä, koska liittyvät massamuokkausten tekemiseen, eikä niitä aleta heti ensimmäiseksi tehdä.

(niina)

**Comment by minna-aaltonen** [comment]
Lisäsin yllä olevat tiedot issueen Niina: Aineistohaku | Hakutulos: Taulukossa ei ole riittäviä tietoja, jotta voitaisiin valita massamuokattavat arkistoyksiköt #172

Suljen tämän niin samasta asiasta ei ole montaa issueta.
