### ISSUE TITLE
perusnäkymän sarakkeet

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#248]
Tästä on keskusteltu kauan sitten. 
Perusnäkymässä kaikki sarakkeet venyvät nyt maailman ääriin. Oli puhetta, että niille laitetaan joku rajoitettu, soveltuvan mittainen leveys, ja loput tekstit rivittyy. Oliko teillä tämä vielä listalla? (niina)

**Comment by minna-aaltonen** [comment]
Tarkoitatko arkistoyksiköiden tietojen näyttämistä taulukossa? Voisitko laittaa kuvan ongelmasta niin ymmärrämme paremmin mistä on kyse? Minusta rivittyvät ja mahtuvat kyllä ruudulle, mutta ehkä katson väärää dataa?

**Comment by KelaTest** [comment]
Olimme vähän hätäisiä. Olet ihan oikeassa, että kaikki tiedot mahtuvat yhdelle sivulle, ja se on pääasia. Kiinnitimme huomion vain siihen, että jos esim. on pitkä nimi ja ei tarkkeria, näytöllä näkyy nimi yhdellä rivillä tosi pitkänä. Mutta kun kaikissa sarakkeissa on tietoja, rivittyvät kyllä ja pääasia siis, että kaikki tiedot näkyvät samalla sivulla. 
Tämän voi sulkea.
