### ISSUE TITLE
Käyttäjärooli vaihtuu 

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#249]
Kirjauduin järjestelmään peruskäyttäjänä.  Avasin järjestelmän toiseen välilehteen, sivu avautui peruskäyttäjänä (??). Kirjauduin ulos ja uudestaan sisään pääkäyttäjänä, testailin. Pidin pienen tauon ja havaitsin roolin muuttuneen peruskäyttäjäksi, toiminta myös peruskäyttäjän mukainen. Kokeilin myös avata kolmannen kerran, nyt aukesi pääkäyttäjänä. (Paula)
ps.jostain tämäntapaisesta on kai raportoitu aiemminkin?

**Comment by KelaTest** [comment]
Olen ollut koko päivän pääkäyttäjänä koneella. Hetki sitten tehtyäni muualla muuta ja palattuani järjestelmään, olenkin siellä peruskäyttäjänä peruskäyttäjätoiminnoin. (niina)

**Comment by minna-aaltonen** [comment]
Vähän samantapainen ongelma oli:  Niina: Sisäänkirjautuminen ja uloskirjautuminen eivät toimi oikein #140
