### ISSUE TITLE
hitautta järjestelmässä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#250]
eilen oli todella jumipäivä noin 12 lähtien; tänään ollut myös joiltain osin merkittävää hitautta, esimerkiksi arkistonmuodostajan sarjojen avaaminen ja hakutulosten saaminen kestää hyvinkin minuutin-minuutteja. (niina)

**Comment by minna-aaltonen** [comment]
Arno, katsotko tätä?
