### ISSUE TITLE
Lainassa oleva aineisto poimiutuu hävityslistalle

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#252]
Tästä ihan kuin olis joku vanha jo? (niina)

**Comment by minna-aaltonen** [comment]
Toiminnallisuudesta ei ole vaatimusta.

**Comment by KelaTest** [comment]
Ei voi jäädä tilannetta, jossa aineiston rivi on hävitetty ja itse aineisto on fyysisesti jossain muualla.

**Comment by KelaTest** [comment]
Paulan sposti 21.4. klo 12.04:
Lainassa olevat aineistot eivät saa nousta hävitysehdotukselle (ja niitä ei saa hävittää). 
Tein hävitysehdotuksen IT-osastolle.(21.4. klo 11.26)
Lisäsin kolmelle hävityskelpoiselle  IT-osaston C.a.- sarjan arkistoyksikölle lainatietoja
-	järj.nro 100:  lainattu ja palautettu
-	jarj.nro 101: lainassa
-	järj.nro 102: yksi palautettu laina + yksi lainassa
Kaikki kolme tulivat hävitysehdotukselle (21.4.klo 11.35). 
(Aika hankala vertailla, kun järjestys on satunnainen ja vaihteleekin näemmä, mutta järjestyksestähän on jo kaiketi tiketti olemassa )
