### ISSUE TITLE
aineistohaku hakukenttien nimien tarkistus

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#254]
Dokumentin "aineistohaut ja massamuokkaus_toimittajalle_2015-04-08.xlsx" mukaisiksi, kiitos!
(esim. säilytysaikatyyppi > Säilytysaika (muu arvo)
(niina)

**Comment by minna-aaltonen** [comment]
Korjattu järkevin osin dokumentin mukaisiksi, esim. Sarjan kenttä **Järjestämiseen liittyvät tiedot** on **Sarjan järjestämiseen liittyvät tiedot** mikä selventää käyttöä, kun valittavana on sarjan, arkistoyksikön ja säilytysyksikön tietoja.
