### ISSUE TITLE
Molemmissa tietoa:  säilytysaika(vuotta) ja säilytysaika(muu arvo)

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#256]
Arkistoyksiköllä 135052 on  tietoa molemmissa kentissä, en ole ainakaan tarkoituksella kirjannut molempiin kenttiin, mutta näin näkyy olevan. ???   (Paula)
![mystista 135052](https://cloud.githubusercontent.com/assets/11074411/7882629/2aaa03dc-0618-11e5-8a6a-46b584e20c09.PNG).

**Comment by KelaTest** [comment]
lisäys: rajavuosikentissä numeroita ja kirjaimia (ei näy leikkeessä).

**Comment by minna-aaltonen** [comment]
Edellinen lisäys ei liity samaan asiaan kuin tämä issue. Tuosta ongelmasta on jo issue: ARKISTOYKSIKKÖ | Rajavuodet: Rajavuosikenttiin voi tallentaa kirjaimia #229

**Comment by minna-aaltonen** [comment]
Tämän uuden issuen myötä taisi selvitä miten tällainen on tilanne on saatu aikaan: ARKISTOYKSIKKÖ | korttien selaus: Tyhjä kenttä ei tyhjene selatessa vaan siinä näkyy edellisen kortin arvo #263 

Suljen tämän issuen ja korjataan tuo toinen. Jos tällaista edelleen ilmenee niin palataan asiaan uudelleen.
