### ISSUE TITLE
Näkymätulosteet

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#257]
Näkymätulosteisessa virheitä:
1. Perusnäkymästä tulostettu tuloste: tyhjä, 1s. 
2. Lisää arkistonmuodostaja-näkymä: tulostaa "lisää arkistonmuodostaja"-ruudun. Alla oleva perusnäkymä ei tule tulosteeseen. 1 sivu.
3. Aineistohakunäkymästä tulostettu tuloste: tyhjä, 1s.
4. Experttihakynäkymästä tulostettu tuloste: tyhjä, 1 s.
5. Hävitysehdotusnäkymästä tulostettu tuloste: Yksi sivu, tekstit on, tulosta- nappi näkyy koodimuodossa ("Tulosta(/export/h%C3[...]). Tekstit skaalautuvat kapeammiksi kuin ruudulla näkyy.
(niina)

**Comment by minna-aaltonen** [comment]
Näkymien tulostamisesta ei ole vaatimuksia.
