### ISSUE TITLE
Perusnäkymä | Arkistonmuodostajalista: Uusi arkistonmuodostaja ei päivity listaan

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#258]
Loin arkistonmuodostajan A tehtäväluokitus. Tieto ei päivittynyt perusnäkymän listaan. Luulin että painoin vahingossa "palaa"-nappia, joten tein toisen samannimisen perään. Sekään ei ilmestynyt listalle. Kokeilin käydä toisella välilehdellä ja palasin takaisin perusnäkymään; tiedot olivat nyt näkyvissä (2 saman nimistä arkmua)
(niina)

**Comment by minna-aaltonen** [comment]
En pysty toistamaan tätä. Toistuuko Niina sinulla?

**Comment by KelaTest** [comment]
Kyllä, pystyin toistamaan virheen. (niina)

**Comment by minna-aaltonen** [comment]
Olithan huomioinut, että arkistonmuodostaja ilmestyy aakkostettuna oikealle paikalleen? Se ei siis välttämättä tule näkyviin näytölle ellei arkistonmuodostajalistaa vieritä ylös/alas? Anteeksi kun kyselen samasta asiasta moneen kertaan, mutta en saa millään toistettua virhettä täällä.

**Comment by KelaTest** [comment]
Kyllä, huomioin sen. Tein niitä aika korkealle aakkosiin, jotta näen heti suoraan miten päivittyy. Ei päivittynyt :) 
Tää on varmaan niitä F5-virheitä mitä tässä on vielä jonkun verran jäljellä. Tämä toinen arkmu oli "B arkmu". (niina)

**Comment by KelaTest** [comment]
Testasin uudelleen siten, että poistin kaiken historiatiedon selaimen välimuistista; kirjauduin ulos sovelluksesta (testaus), suljin selaimen ja koneen, kirjauduin normijärjestyksessä takaisin (tuotantoon) ja hyvin toimii. Eli en pystynyt enää toistamaan virhettä. (niina)

**Comment by KelaTest** [comment]
En pystynyt toistamaan. (Paitsi siten, että valitsin Päättyneet Kelan arkistonmuodostajat näkyville, ja kirjasin uuden  aktiivisen arkistonmuodostajan, mutta näin Niina ei varmaankaan ollut tehnyt, koska toisti saman ..?)  (Paula)

**Comment by minna-aaltonen** [comment]
Paulan kuvaamassa tapauksessa arkistonmuodostajan ei kuuluisi listalle ilmestyäkään. Tehdään tälle taas niin, että suljetaan, mutta palataan asiaan, jos tämän kanssa vielä ilmenee ongelmia.
