### ISSUE TITLE
Raportit | Näytä aineistotilasto: Aineistotilasto ei päivity näytölle lainkaan ja jumittaa selaimen

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#259]
Odoteltu 10-20 min aineistotilaston valmistumista IE11 ja Firefox selaimilla, ei tule valmista.

Irrotetaan tähä issueen suorituskykyongelma issuesta:
Aineistotilasto; suorituskykyongelma ja muut huomiot #246

**Comment by KelaTest** [comment]
KOTTO tuotanto: Aineistotilasto ei päivity ja jumittaa selaimen edelleen. Odoteltu 30 minuuttia IE11:lla.

**Comment by minna-aaltonen** [comment]
Tätä ei ole korjattu vielä.
