### ISSUE TITLE
Tyhjien säilytysyksiköiden poistaminen

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#260]
Arkistoyksiköiden hävitysten yhteydessä tyhjäksi jääneet säilytysyksiköt jäävät kantaan. Näitä ei pysty hakemaan eikä poistamaan millään massatoiminnallisuudella. Haittaavat hakuja, kun hakutuloksistakaan ei näy heti, mitkä säilytysyksiköt ovat tyhjiä. Tyhjiin säilytysyksiköihin ei ole otettu kantaa vaatimuksissa, koska sellaista käsitettä ei ollut, säilytysyksikön tiedot olivat suoraan arkistoyksikön tietoja. Tästä on kyllä keskusteltu, mutta ei taidettu sopia vielä mitään.. (paula)

**Comment by minna-aaltonen** [comment]
Menisikö sääntö niin, että aina kun säilytysyksiköstä viimeinen arkistoyksikkö, myös säilytysyksikkö poistetaan järjestelmästä?

**Comment by KelaTest** [comment]
Mieluummin haku, kiitos! (niina)
