### ISSUE TITLE
Aineistohaun hakutulosten selauksessa virheitä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#261]
Selasin oikean yläkulman nuolinäppäimillä hakutuloksia. Pari outoa tilannetta tuli vastaan, katso liitteet.Testasin silloin hävitystoiminnallisuutta, joten ko. arkistoyksiköitä on ehkä hävitetty, mutta leikkeistä näkyy millaiselta näyttivät. (Paula)
![virhe13](https://cloud.githubusercontent.com/assets/11074411/7956588/6ec06276-09e9-11e5-9e68-4b6eac1f8b3d.PNG)
![virhe14](https://cloud.githubusercontent.com/assets/11074411/7956594/75b2a6fc-09e9-11e5-92e3-ba0437d90216.PNG)

**Comment by minna-aaltonen** [comment]
Olen pahoillani, mutta nyt en kyllä keksi mitä näissä liiteenä olevissa kuvissa on pielessä. Voisitko hiukan avata, kun nyt en kyllä hokaa?

**Comment by KelaTest** [comment]
Molemmissa nimen tarkenne ei kuulu ko.arkistoyksikölle. Ja alempi avautunut arkistoyksikkö ei näytä kuuluvan hakutuloksiin (avautuneen kortin takana näkyy hakutulokset, nimi ja tarkenne)

**Comment by KelaTest** [comment]
Jaahas, tarkemmin katsoen ei ilmeisesti yrittänytkään selata hakutuloksia, vaan arkistoyksiköitä kaavan mukaisessa järjestyksessä..  mutta nimen tarkenne-kentässä ainakin ongelmaa, en tarkastellut mitenkään muita kenttiä.

**Comment by minna-aaltonen** [comment]
Havainto on oikea, eli selaa kaavan mukaisessa järjestyksessä, eikä hakutuloksia.

Tätä penkoessa huomasin tällaisen:  ARKISTOYKSIKKÖ | korttien selaus: Tyhjä kenttä ei tyhjene selatessa vaan siinä näkyy edellisen kortin arvo #263 

Ymmärtääkseni tämä kattaa tässä issuessa havaitut ongelmat. Suljen tämän issuen ja jatketaan keskustelua tarvittaessa siellä.
