### ISSUE TITLE
Ohjeet: eksperttihaun ohjeeseen täydennystä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#262]
Pari täydennystoivetta ohjeeseen:  
-haku tekstikentän arvon perusteella (eli  "-hipsut pitää laittaa) 
-onko mahdollista hakea osasanalla tms?
-haku päivämäärän perusteella (on kyllä esimerkeissä, mutta ne voivat kadota)
-arkistoyksikön id:n kenttänimeä ei ole kerrottu hallinta-välilehdellä. jos hankalaa lisätä sinne,voisi mainita ohjeessa.  (paula)

**Comment by minna-aaltonen** [comment]
Ohje päivitetty:
https://github.com/Proactum/ARTI/blob/master/documentation/2.3%20Eksperttihaku.md
