### ISSUE TITLE
ARKISTOYKSIKKÖ | korttien selaus: Tyhjä kenttä ei tyhjene selatessa vaan siinä näkyy edellisen kortin arvo

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#263]
Kun tietokortteja selaa niin tietokorttien kentät eivä tyhjene, jos arvo on tyhjä seuraavissa kentissä:
* **Ala-arkistonmuodostaja**
* **Nimen tarkenne**
* **Lisätiedot**
* **Aineiston kuvailu**
* **Rajavuodet, tarkenne**
* **Säilytysaika (vuotta)**
* **Säilytysaika (muu arvo)**
* **Näyte, otanta**
* **Salassapitoaika (vuotta)**
* **Salassapitoperuste**
* **Salassapidon päättymisajankohta**
* **Aineistoviite**
* **Kielet**
* **Järjestämiseen liittyvät tiedot**
* **Poistettu hävitysehdotukselta**

**Comment by minna-aaltonen** [comment]
Ei ole korjaantunut QA:lla 16.6.2015.

**Comment by ArnoSaine** [comment]
ny(?)
