### ISSUE TITLE
viimeisin kirjaaja ja kirjauspäivä ei näy missään

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#265]
Ei nähdä mistään "leimaustietoja". Tästä ollaankin jossain palaverissa yhdessä keskusteltu . (Paula)

**Comment by minna-aaltonen** [comment]
En löytänyt vaatimusta tällaiselle toiminnallisuudelle. Kertoisitko missä kohtaa vaatimusdokumenttia tätä on vaadittu?
