### ISSUE TITLE
Hävitysehdotus-excel ei saa päivittyä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#267]
Loin ja tulostin hävitysehdotuksen ja tein sen jälkeen muutoksia hävitysehdotuksella olevaan aineistoon (=mm. muutin säilytysaikaa ja lisäsin julkisuus- ja henkilötietoja). Menin sen jälkeen katsomaan samaa hävitysehdotusta uudestaan, ja em tiedot näkyivät päivittyneenä. Päivittyminen sekoittaa,

 ja hämärtää mm sen ymmärtämistä,  että hävitysehdotus on tässä tilanteessa ehdottomasti luotava kokonaan uudestaan ennen sen hyväksymistä. (Paula)

**Comment by minna-aaltonen** [comment]
Tarkennus: Arkistoyksiköiden listalta ei poistu arkistoyksiköitä vaikka arkistoyksikköjen tietoja päivitettäisiin. Arkistoyksikkö poistuu hävitysehdotukselta ainoastaan jos se on kokonaan poistettu järjestelmästä. Arkistoyksikköjä ei myöskään lisätä jo luodulle hävitysehdotukselle, vaikka niiden tietoja muutetaan niin, että ne voisivat sinne nousta. Ongelma liittyy siis pelkästään siihen, että hävitysehdotuksella olevien arkistoyksikköjen tiedot ovat ajantasaisia, jos Excel tulostetaan uudelleen arkistoyksköiden muokkaamisen jälkeen.
