### ISSUE TITLE
Arkistoluetteloa ei voi tulostaa

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#272]
usean minuutin odottelun jälkeen antaa virheilmoituksen 

Proxy Error

The proxy server received an invalid response from an upstream server.
 The proxy server could not handle the request GET /_export/arkistoluettelo.

Reason: Error reading from remote server

Apache/2.2.22 (Debian) Server at arti.kela.fi Port 443

**Comment by ArnoSaine** [comment]
Saattoi koskea vain arkistonmuodostajia, joiden kuvailutieto on tyhjä. Siinä tapauksessa tämä on korjattu.
