### ISSUE TITLE
Arkistonmuodostajan poistaminen tapahtuu ilman varmennuskysymystä

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#48]
Kun arkistonmuodostaja-näytöllä painaa poista-painiketta, arkistonmuodostajan tiedot häviävät välittömästi. Pitäisi tulla jonkinlainen varmentava kysymys, jotta voi vielä peruuttaa poistamisen.

**Comment by minna-aaltonen** [comment]
Testattu OK. Nyt tulee varmistusdialogi: "Haluatko varmasti poistaa arkistonmuodostajan ja sen mahdollisesti sisältämät arkistoyksiköt?" Poista/Palaa.
