### ISSUE TITLE
Arkistoyksikkö-näytön alasvetovalikoista puuttuu 'tyhjä' vaihtoehto

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#49]
Kaikissa arkistoyksikkö-näytön alasvetovalikoissa pitäisi olla vaihtoehto 'tyhjä' , joka olisi myös oletusarvona uuden kirjauksessa. Tiedot Säilytysaikatyyppi ja Säilytysaika ovat vaihtoehtoisia, joten näistä toisen tulee aina olla tyhjä. Lisäksi tyhjä tieto kertoo, että asiaan ei ole vielä otettu kantaa.

**Comment by mustakostaja** [comment]
Tehty.
