### ISSUE TITLE
Hävitettävissä-tiedon laskennassa virhe (arkistoyksikön tieto)

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#50]
Jos valitsee säilytysaikatyypiksi Toistaiseksi, järjestelmä laskee Hävitettävissä-tiedon arvoksi aina viimeinen rajavuosi + 1, riippumatta annetusta Säilytysajasta. Jos valitsee Säilytysaikatyypiksi jonkun muun, tuo Hävitettävissä-tiedossa tyhjää.

**Comment by MetkaDev1** [comment]
Mitkä kentät pitäisi vaikuttaa hävitettävissä arvoon ja kuinka?
Onko siis niin, että jos säilytysaikatyyppi on toistaiseksi, niin silloin lasketaan tämä vuosi esim. 2015 + säilytysaika (vuotta) + 1 vuotta?

**Comment by KelaTest** [comment]
Hei,
Säilytysaikatyyppi ja säilytysaika (vuotta) ovat vaihtoehtoisia.
Säilytysaikatyypistä valittavat  arvot ovat:
1. voa+3
2. voa+6
3. voa+10
4. sp
5. toistaiseksi
Jos säilytysaikatyyppiin on valittu jokin arvo niin hävitettävissä kentässä  näytetään arvo 9999 tai tyhjää.

Terv. Matti
040 1972 316

Lähettäjä: MetkaDev1 [mailto:notifications@github.com]
Lähetetty: 26. helmikuuta 2015 10:06
Vastaanottaja: Proactum/ARTI
Kopio: Happonen Matti
Aihe: Re: [ARTI] Hävitettävissä-tiedon laskennassa virhe (arkistoyksikön tieto) (#50)


Mitkä kentät pitäisi vaikuttaa hävitettävissä arvoon ja kuinka?
Onko siis niin, että jos säilytysaikatyyppi on toistaiseksi, niin silloin lasketaan tämä vuosi esim. 2015 + säilytysaika (vuotta) + 1 vuotta?

**Comment by KelaTest** [comment]
Paulan lisäys: Hävitettävissä-tieto lasketaan vain, jos on annettu säilytysaika(vuotta)-tieto. Laskentasääntö: hävitettävissä = arkistoyksikön rajavuodet (loppuvuosi) + säilytysaika + 1.  Jos arkistoyksikölle on annettu säilytysaikatyyppi, niin arkistoyksikköä ei hävitetä hävitystoiminnallisuuden kautta eikä hävitettävissä- tietoa käytetä  (kantaan voi silloin viedä 9999, mutta näytöllä voisi näyttää tyhjää). Tarkoitus on, että kaikille arkistoyksiköille kirjataan vuosiluku-muotoinen loppu-rajavuosi.

**Comment by mustakostaja** [comment]
Korjattu laskenta kaava: hävitettävissä = arkistoyksikön rajavuodet (loppuvuosi) + säilytysaika + 1.
Jos säilytysaikatyyppi on valittus, hävitettävissä on tyhjä.

**Comment by minna-aaltonen** [comment]
Testattu, toimii kuten tässä suunniteltu.
