### ISSUE TITLE
Klikkaus Arkistoyksikkö-ikkunan ulkopuolelle toimii kuten Palaa-painike

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#52]
.. eli tapahtuma keskeytyy harmillisesti ilman tietojen tallennusta. (Palaaminen ilman tietojen tallennusta onnistuu 'laillisesti' Palaa-painikkeesta ja oikean yläkulman ruksista.)

**Comment by minna-aaltonen** [comment]
Estetty ponnahdusikkunan sulkeminen ohikikkauksella ja ESC-näppäimellä.

**Comment by minna-aaltonen** [comment]
Virhe palasi.

**Comment by minna-aaltonen** [comment]
Virhe poistui jälleen.
