### ISSUE TITLE
Arkistoyksiköiden selaus ei toimi Arkistoyksikkö-ikkunassa

### ISSUE THREAD

**Issue by KelaTest** [Proactum/ARTI#54]
Arkistoyksikkö-näytön oikeassa yläkulmassa olevat selausnuolet eivät toimi.

**Comment by minna-aaltonen** [comment]
Tätä toiminnallisuutta ei ole toteutettu vielä. Nyt selausnuolet on merkitty keltaisella eli ovat vasta työn alla.
