### ISSUE TITLE
Sarjan siirto: Pääsarjan siirto oman alasarjansa alle kadottaa pääsarjan

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#60]
Pääsarja ja kaikki sen alla olevat tiedot katoavat, jos pääsarjan siirtää oman alasarjansa alle.

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)

**Comment by minna-aaltonen** [comment]
Korjaus on se, että sarjan siirtäminen itsensä alle on kielletty. Jos sarja halutaan siirtää itsensä alle, pitää ensin siirtää alla oleva sarja pääsarjaksi ja sitten siirtää entinen pääsarja sen alle.

Jos halutaan veivata sarjoja seuraavasti:
A
  A.b
-> 
b
 b.A

Pitää ensin siirtää A.b -> b ja sitten A -> b.a

Sarjojen sijaintien muuttamisessa on edelleen vakavia virheitä ja ne on kuvattu issuessa: Sarjojen sijainnin muutokset kadottavat sarjoja #61
