### ISSUE TITLE
Sarjojen sijainnin muutokset kadottavat sarjoja

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#61]
**Katso seuraava kommentti, näistä osa on jo ok**
Kun Arkistonmuodostaja ponnahdusikkunassa siirretään sarjoja:
* pääsarjaksi 
* toisen pääsarjan alle tai 
* toisen pääsarjan alasarjan alle 

siirrot kyllä toimivat, mutta tieto päivittyy Arkistonmuodostaja ponnahdusikkunaan vasta, kun ponnahdusikkuna on avattu uudelleen.

**Comment by minna-aaltonen** [comment]
**OSITTAIN KORJATTU**: 

Nyt ongelmana on enää pääsarjan siirtäminen toisen pääsarjan alle, se ei päivity Arkistonmuodostaja ponnahdusikkunaan vaikka muutos kyllä tallentuu ja tiedot uudelleen hakien tulee näkyviin.

**Comment by mustakostaja** [comment]
Tainnut jo korjaantua.

**Comment by minna-aaltonen** [comment]
Ei ole vielä korjaantunut.

**pääsarjan siirtäminen toisen pääsarjan alle**

Luo sarjat:
* Pääsarja A
* Pääsarja B

Siirrä pääsarja B sarjan A alle. -> Sarja B katoaa (tulee näkyviin kun **ARKISTONMUODOSTAJA** kortti avataan uudelleen).

**alasarjan siirtäminen alaspäin sarjahierarkiassa saman pääsarjan alla***
Luo sarjat:
* pääsarja A 
* A:n alle sarja A.a
* A:n alle sarja A.b

Siirrä A.b sarjan A.a alle -> sarja A.b katoaa (tulee näkyviin kun **ARKISTONMUODOSTAJA** kortti avataan uudelleen).

**alasarjan siirtäminen ylöspäin sarjahierarkiassa saman pääsarjan alla**
* Tämä näyttää korjaantuneen.

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)

**Comment by minna-aaltonen** [comment]
No nyt toimivat sarjojen siirrot.
