### ISSUE TITLE
Perusnäkymän Arkistokaava ja sarjat taulukko ei päivity kun poistetaan peräkkäin kaksi arkistoyksikköä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#62]
Kun samalta arkistonmuodostajalta poistetaan peräkkäin kaksi arkistoyksikköä, jälkimmäinen poisto ei päivity oikein Päänäkymän Arkistokaava ja sarjat taulukkoon. Kun sivu ladataan uudeelleen nähdään, että toinenkin arkistoyksikkö on kyllä poistunut.

**Comment by minna-aaltonen** [comment]
Ei ole korjaantunut QA:lla ainakaan  vielä 10.4.2015 klo 11:16.

**Comment by minna-aaltonen** [comment]
Ei ole korjaantunut QA:lla 16.4.2015.

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)

**Comment by minna-aaltonen** [comment]
Nyt arkistoyksiköiden poistot päivittyvät Perusnäkymässä.
