### ISSUE TITLE
Perusnäkymä: Arkistokaava ja sarjat taulukko ei päivity kun siirretään arkistoyksikkö eri sarjan alle

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#65]
Kun Päänäkymässä siirtää arkistoyksikön toiseen sarjaan niin arkistoyksikkö poistuu heti vanhan sarjan alta, mutta ei tule näkyviin uuden sarjan alle ennen kuin sivu on päivitetty uudelleen.

**Comment by minna-aaltonen** [comment]
Jos ensin siirtää sarjaa ja sen jälkeen muokkaa arkistoyksikön tietoja ja tallentaa, tulee Oops! virheilmoitus. (Niinan havainto 2.4.2015)

**Comment by minna-aaltonen** [comment]
Muuttunut sarjatieto ei näy myöskään **ARKISTOYKSIKKÖ** kortilla vielä silloinkaan, kun arkistoyksikkö on siirtynyt **Perusnäkymä**:ssä oikean sarjan alle. (Paulan havainto 17.4.2015)

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)

**Comment by minna-aaltonen** [comment]
Nyt toimii niin, että jos ARKISTOYKSIKKÖ kortilla valitaan **Vaihda arkistonmuodostajaa ja sarjaa** ja sitten **Tallenna** niin ARKISTOYKSIKKÖ kortti sulkeutuu ja arkistoyksikkö siirtyy oikeaan paikkaan **Perusnäkymä** näytöllä. Kaikki yllä mainitut ongelmat ovat muutosten myötä korjaantuneet.
