### ISSUE TITLE
Säilytysyksikköjen haku ei huomioi poistetuiksi merkittyjä säilytysyksikköjä -> virheilmoitus

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#66]
Näin toistat:
1) Luo säilytysyksikkö
2) Hae säilytysyksikkö
3) Poista säilytysyksikkö
4) Hae säilytysyksikköä uudelleen (sivu täytyy uudelleenladata, jotta säilytyyksikkö katoaa hakutuloksista) -> "Oops! Odottamaton virhe. Tiedot tallennettu lokiin."

**Haku:**

https://kela-qa.demo.proactum.fi/_db/sailytysyksikot/_changes?filter=schema/search

**Post:** {"säilytysyksikkö":{"min":"1003","max":""}}

**Response:**
{"results":[
{"seq":25,"id":"1003","changes":[{"rev":"2-c08856c506ea0bce55faeb432c7b1fdf"}],"deleted":true}
],
"last_seq":25}

**Tiedot koitetaan hakea näytölle:**
https://kela-qa.demo.proactum.fi/_db/sailytysyksikot/1003

**Response:**
{"error":"not_found","reason":"deleted"}

**Comment by KelaTest** [comment]
Jos ymmärsin oikein, eli että poistetut säilytysyksiköt eivät näy hakutuloksissa, silloinhan se toimii just niin kuin toivomme. Eli emmehän me haluakaan hakea sellaisia säilytysyksiköitä, joita ei enää ole olemassa.

**Comment by minna-aaltonen** [comment]
Tämä on jonkin vikakorjauksen yhteydessä näemmä jo korjaantunut. Alkuperäinen ongelma oli tuo Ooops virheilmoitus, ei suinkaan se, että olematonta säilytysyksikköä ei näytetä.
