### ISSUE TITLE
Niina: Hävitysluettelon poistaminen ei ole mahdollista

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#69]
**Pääkäyttäjän** pitäisi voida poistaa hävitysluettelo. Jos hävitysluettelo on hyväksytty vahingossa tai väärin perustein, sitä ei voi enää mitenkään poistaa järjestelmästä. Tästä ei ole käsittääkseni ole selvää vaatimusta suuntaan eikä toiseen (että pitäisi voida poistaa tai että hyväksyttyä ei saa poistaa) eikä sitä ole suunnitelluissa rautalangoissa, mutta jos on mahdollista, että hävitysehdotuksen hyväksymistä joskus kadutaan, olisi hyvä, että hävityluettelon voisi poistaa hävittämättä sillä olevia aineistoja.

Expected: HÄVITYSLUETTELO ponnahdusikkunassa pitäisi olla Poista nappi.

31.3.2015 myös Niina kyseli: "Onko mahdollista lisätä hävitysluettelo-sivulle hävitysluetelon poisto-nappulan pääkäyttäjää varten?"

**Comment by minna-aaltonen** [comment]
Niina tiedusteli myös: Onko mahdollista lisätä hävitysluettelo-sivulle hävitysluetelon poisto-nappulan pääkäyttäjää varten?

**Comment by KelaTest** [comment]
Totesimme 27.5. taas tämän "puutteen" ja katselimme siinä samalla rautalangat. Mielestämme ne oli tarkoitettu niin ,että hävitysehdotus-sivu on samanlainen kuin hävitysluettelosivu, siksi siitä ei ollut erillistä kuvaakaan. Toiminto olisi hyvä olla, aina voiolla joku erityistilanne, että luetteloa ei ajeta ja tarvitsisi poistaa. N&P

**Comment by KelaTest** [comment]
Kela tsekannut, ok > voi siirtää tuotantoon

**Comment by KelaTest** [comment]
Hei, 

huomasin juuri, että toimii myös peruskäyttäjällä. Piti olla vain pääkäyttäjälle. NiinaV
