### ISSUE TITLE
Aineiston poisto aiheuttaa päivitysongelmia Hävitysehdotus näkymässä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#74]
Jos jollakin hävitysehdotuksella ollut aineisto poistetaan järjestelmästä manuaalisesti Hävitysehdotus näkymän listassa ei näy yhtään hävitysehdotusta ennen kuin sivu on ladattu uudelleen.

Sukua ongelmalle:  Poistetun arkistonmuodostajan hävitysehdotukset aiheuttavat virheen #63

**Comment by ArnoSaine** [comment]
fixed: f59b7a4a66dc7298cbbd50817946248cf33c0149
