### ISSUE TITLE
Niina: Arkistonmuodostaja | Arkistokaava taulukko: Sarjat eivät näy tunnuksen mukaan aakkosjärjestyksessä

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#87]
Edes tietojen hakeminen uudelleen ei järjestä vasta luodun arkistokaavan sarjoja oikein:

![06 arkistonmuodostajan arkistokaava taulukossa sarjat eivat ole aakkosjarjestykessa](https://cloud.githubusercontent.com/assets/8858834/6894122/8298b6ae-d6db-11e4-9b43-d1b8df9b56c5.png)

"SARJAT: JoS tallentaa sarja "B", "B." ja "C", näyttää järjestyksessä "B", "C", "B." (johtuuko tekstin pituussäännöstä, vaikka yksi arvo on piste)"

**Comment by KelaTest** [comment]
Nämä ovat mielestämme kiireellisiä korjattavia. (niina&paula)

**Comment by minna-aaltonen** [comment]
Nyt sarjojen tunnukset aakkostuvat oikein ARKISTONMUODOSTAJA dialogissa.
