### ISSUE TITLE
Niina: Arkistonmuodostaja | Arkistokaava: Tunnuksen ja Nimen väli kapeampi konversiolla tuoduissa aineistoissa kuin käsin luodussa aineistossa

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#96]
Minna havaitsi saman ilmiön. Mikäköhän lienee syynä?

"ARKISTONMUODOSTAJANÄKYMÄ: tänään (30.3.) luoduissa arkistonmuodostajissa Arkistokaavassa Tunnuksen ja Nimen väli on mystisesti paljon pidempi, kuin konversiossa vietyjen arkistojen arkistokaavoissa"

**Comment by ArnoSaine** [comment]
Sarakeleveydet sovitetaan sisällön pituuden mukaan.
